"""The Atlas metadata GraphQL schema (R11-GQL01, design section 13A).

Typed metadata reads -- datasources, tables, columns, constraints and approved
descriptions -- with cursor paging. Every resolver is a thin call into
`aida.graphql_reads`, which makes the decision the equivalent REST route makes;
no resolver builds a query of its own, imports a router, or calls over HTTP.

**Queries never reach a source.** No `Query` field reaches a connector or the query
gateway. Governed execution is one explicit mutation, `executeGovernedTool`
(R11-GQL02, `aida.governed_execution`): an approved tool version through the same
path as REST, once per caller-scoped idempotency key. Its rows appear only in that
mutation's response; the `governedExecution` query returns the receipt, which has no
rows by construction. There is no subscription. No type a query can reach
carries a source value either -- no column default, partition bound, view or
routine body, profile statistic or sample row; the metadata types expose what the
REST reads expose and nothing more (`tests/test_graphql_api.py` scans for it).

**Refusals are per field.** A field the caller may not read resolves to `null`
with an error whose `extensions.code` is stable and whose message is that code.
Every such field is nullable on purpose, so one forbidden branch does not erase
its permitted siblings.

The published SDL is `Docs/90-reference/graphql-schema.graphql`, regenerated by
`scripts/generate_graphql_schema.py`. `GRAPHQL_SCHEMA_VERSION` is the contract
version: a breaking change to the schema must come with a new version, which
the generator enforces.
"""

from __future__ import annotations

from collections.abc import Callable, Coroutine
from datetime import datetime
from typing import Any, cast
from uuid import UUID

import strawberry
import structlog
from graphql import GraphQLError
from strawberry.extensions import (
    DisableIntrospection,
    MaxAliasesLimiter,
    MaxTokensLimiter,
    QueryDepthLimiter,
    SchemaExtension,
)
from strawberry.scalars import JSON
from strawberry.schema.config import StrawberryConfig
from strawberry.types import ExecutionContext
from strawberry.types.field import StrawberryField

from aida.governed_execution import (
    ExecutionOutcome,
    ExecutionRefused,
    execute_governed_tool,
    list_receipts,
    load_receipt,
)
from aida.governed_execution_models import GovernedExecutionRequest
from aida.graphql_limits import DEFAULT_LIMITS
from aida.graphql_reads import (
    ColumnDescription,
    Page,
    ReadRefused,
    ReadScope,
    TableDescription,
    column_business_description,
    get_datasource,
    get_table,
    list_columns,
    list_constraints,
    list_datasource_tables,
    list_datasources,
    list_organization_tables,
    list_tables,
    referenced_table,
    table_description,
)
from aida.models import MetadataTable
from aida.schemas import (
    DataSourceSummaryRead,
    MetadataColumnRead,
    MetadataConstraintRead,
    MetadataTableRead,
)
from atlas.platform.context import get_correlation_id

__all__ = ["GRAPHQL_SCHEMA_VERSION", "metadata_schema"]

#: The published contract version. Bump it with any breaking change to the SDL;
#: `scripts/generate_graphql_schema.py` refuses to publish a breaking change
#: under an unchanged version.
GRAPHQL_SCHEMA_VERSION = "1"

_log = structlog.get_logger(__name__)

Info = strawberry.Info[ReadScope, None]

_DEFAULT_PAGE = 20

_Resolver = Callable[..., Coroutine[Any, Any, Any]]


def field_resolver(description: str) -> Callable[[_Resolver], StrawberryField]:
    """`@strawberry.field(description=...)`, with a type strict mypy can see.

    Strawberry types its keyword-only `field(...)` overload as returning `Any` (it
    doubles as a plain field default), which makes every decorated resolver
    "untyped" under `mypy --strict`. Passing the resolver positionally selects
    the overload that returns a `StrawberryField` -- the same object the
    decorator form builds. `scripts/generate_surface_control_matrix.py` finds
    resolvers by this decorator's name.
    """

    def decorate(resolver: _Resolver) -> StrawberryField:
        return strawberry.field(resolver, description=description)

    return decorate


def _id(value: UUID) -> strawberry.ID:
    return strawberry.ID(str(value))


def _uuid(value: strawberry.ID) -> UUID:
    try:
        return UUID(str(value))
    except ValueError as exc:
        raise ReadRefused("INVALID_ARGUMENT", "INVALID_ID") from exc


@strawberry.type(description="Where a page ends and whether another follows it.")
class PageInfo:
    has_next_page: bool
    end_cursor: str | None = strawberry.field(
        description="Pass as `after` for the next page. The same opaque keyset cursor "
        "the equivalent REST route returns as `next_cursor`."
    )


def _page_info(page: Page[Any]) -> PageInfo:
    return PageInfo(has_next_page=page.has_next_page, end_cursor=page.end_cursor)


@strawberry.type(
    description="A registered source system, as `GET /v1/datasources/{id}` returns it."
)
class DataSource:
    id: strawberry.ID
    organization_id: strawberry.ID
    project_id: strawberry.ID
    line_of_business_id: strawberry.ID
    data_domain_id: strawberry.ID
    name: str
    connector_type: str
    dialect: str
    environment: str
    network_zone: str
    status: str
    max_concurrency: int
    created_at: datetime
    updated_at: datetime
    read: strawberry.Private[DataSourceSummaryRead]

    @classmethod
    def of(cls, read: DataSourceSummaryRead) -> DataSource:
        return cls(
            id=_id(read.id),
            organization_id=_id(read.organization_id),
            project_id=_id(read.project_id),
            line_of_business_id=_id(read.line_of_business_id),
            data_domain_id=_id(read.data_domain_id),
            name=read.name,
            connector_type=read.connector_type,
            dialect=read.dialect,
            environment=read.environment,
            network_zone=read.network_zone,
            status=read.status,
            max_concurrency=read.max_concurrency,
            created_at=read.created_at,
            updated_at=read.updated_at,
            read=read,
        )

    @field_resolver("This datasource's tables, as `GET /v1/datasources/{id}/tables`.")
    async def tables(
        self,
        info: Info,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        object_type: str | None = None,
        status: str = "ACTIVE",
    ) -> TableConnection | None:
        page = await list_tables(
            info.context,
            self.read,
            first=first,
            after=after,
            q=q,
            object_type=object_type,
            status=status,
        )
        return TableConnection.of(page)


@strawberry.type(description="A table, view or other relation, as the catalog records it.")
class Table:
    id: strawberry.ID
    datasource_id: strawberry.ID
    schema_id: strawberry.ID
    name: str
    object_type: str
    status: str
    fingerprint: str
    row: strawberry.Private[MetadataTable | None]

    @classmethod
    def of(cls, read: MetadataTableRead, row: MetadataTable | None = None) -> Table:
        return cls(
            id=_id(read.id),
            datasource_id=_id(read.datasource_id),
            schema_id=_id(read.schema_id),
            name=read.name,
            object_type=read.object_type,
            status=read.status,
            fingerprint=read.fingerprint,
            row=row,
        )

    @classmethod
    def of_row(cls, row: MetadataTable) -> Table:
        return cls.of(MetadataTableRead.model_validate(row), row)

    def _subject(self) -> MetadataTable | UUID:
        """What a child read is about. A table reached through a list carries only its
        id; the read service loads it with its siblings and decides it on its own --
        the same table-level decision `GET /v1/tables/{id}/columns` makes."""
        return self.row if self.row is not None else _uuid(self.id)

    @field_resolver("The datasource this table belongs to.")
    async def datasource(self, info: Info) -> DataSource | None:
        return DataSource.of(await get_datasource(info.context, _uuid(self.datasource_id)))

    @field_resolver("Active columns in ordinal order, as `GET /v1/tables/{id}/columns`.")
    async def columns(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> ColumnConnection | None:
        table, page = await list_columns(info.context, self._subject(), first=first, after=after)
        return ColumnConnection.of(page, table)

    @field_resolver(
        "Keys and references, as `GET /v1/tables/{id}/constraints`. A referenced "
        "table is authorized on its own."
    )
    async def constraints(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> ConstraintConnection | None:
        page = await list_constraints(info.context, self._subject(), first=first, after=after)
        return ConstraintConnection.of(page)

    @field_resolver("The approved description, as `GET /v1/tables/{id}/description`.")
    async def description(self, info: Info) -> ApprovedTableDescription | None:
        found = await table_description(info.context, self._subject())
        return ApprovedTableDescription.of(found)


@strawberry.type(description="A column's metadata. Never a value from it.")
class Column:
    id: strawberry.ID
    name: str
    ordinal_position: int
    physical_type: str
    nullable: bool
    classification: str
    classification_source: str
    status: str
    source_description: str | None
    table: strawberry.Private[MetadataTable]

    @classmethod
    def of(cls, read: MetadataColumnRead, table: MetadataTable) -> Column:
        return cls(
            id=_id(read.id),
            name=read.name,
            ordinal_position=read.ordinal_position,
            physical_type=read.physical_type,
            nullable=read.nullable,
            classification=read.classification,
            classification_source=read.classification_source,
            status=read.status,
            source_description=read.source_description,
            table=table,
        )

    @field_resolver(
        "The current approved column description, as "
        "`GET /v1/tables/{id}/column-documentation` reads it."
    )
    async def business_description(self, info: Info) -> ApprovedColumnDescription | None:
        found = await column_business_description(info.context, self.table, _uuid(self.id))
        return ApprovedColumnDescription.of(found) if found is not None else None


@strawberry.type(description="A primary, unique or foreign key.")
class Constraint:
    id: strawberry.ID
    table_id: strawberry.ID
    name: str
    constraint_type: str
    columns: list[str]
    referenced_table_id: strawberry.ID | None
    referenced_columns: list[str]
    status: str
    read: strawberry.Private[MetadataConstraintRead]

    @classmethod
    def of(cls, read: MetadataConstraintRead) -> Constraint:
        return cls(
            id=_id(read.id),
            table_id=_id(read.table_id),
            name=read.name,
            constraint_type=read.constraint_type,
            columns=list(read.columns),
            referenced_table_id=(
                _id(read.referenced_table_id) if read.referenced_table_id is not None else None
            ),
            referenced_columns=list(read.referenced_columns),
            status=read.status,
            read=read,
        )

    @field_resolver("The referenced table, authorized on its own; null when it is absent.")
    async def referenced_table(self, info: Info) -> Table | None:
        row = await referenced_table(info.context, self.read)
        return Table.of_row(row) if row is not None else None


@strawberry.type(description="The approved (maker-checker reviewed) table description.")
class ApprovedTableDescription:
    table_id: strawberry.ID
    name: str
    source_description: str | None
    readme: str | None
    readme_version: int | None
    approved_by: str | None
    approved_at: datetime | None
    withdrawn_readme: str | None

    @classmethod
    def of(cls, found: TableDescription) -> ApprovedTableDescription:
        return cls(
            table_id=_id(found.table_id),
            name=found.name,
            source_description=found.source_description,
            readme=found.readme,
            readme_version=found.readme_version,
            approved_by=found.approved_by,
            approved_at=found.approved_at,
            withdrawn_readme=found.withdrawn_readme,
        )


@strawberry.type(description="The approved (maker-checker reviewed) column description.")
class ApprovedColumnDescription:
    description: str
    version: int
    approved_by: str | None
    approved_at: datetime | None

    @classmethod
    def of(cls, found: ColumnDescription) -> ApprovedColumnDescription:
        return cls(
            description=found.description,
            version=found.version,
            approved_by=found.approved_by,
            approved_at=found.approved_at,
        )


@strawberry.type(description="A page of datasources.")
class DataSourceConnection:
    nodes: list[DataSource]
    page_info: PageInfo
    total_count: int | None = strawberry.field(
        description="Computed on the first page only (no `after`), as REST computes `total`."
    )

    @classmethod
    def of(cls, page: Page[DataSourceSummaryRead]) -> DataSourceConnection:
        return cls(
            nodes=[DataSource.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of tables.")
class TableConnection:
    nodes: list[Table]
    page_info: PageInfo
    total_count: int | None = strawberry.field(
        description="Computed on the first page only, and only over what the caller may read."
    )

    @classmethod
    def of(cls, page: Page[MetadataTableRead]) -> TableConnection:
        return cls(
            nodes=[Table.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of columns.")
class ColumnConnection:
    nodes: list[Column]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[MetadataColumnRead], table: MetadataTable) -> ColumnConnection:
        return cls(
            nodes=[Column.of(item, table) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of constraints.")
class ConstraintConnection:
    nodes: list[Constraint]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[MetadataConstraintRead]) -> ConstraintConnection:
        return cls(
            nodes=[Constraint.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="Metadata reads. Nothing here executes against a source.")
class Query:
    @field_resolver("One datasource by id, as `GET /v1/datasources/{id}`.")
    async def datasource(self, info: Info, id: strawberry.ID) -> DataSource | None:
        return DataSource.of(await get_datasource(info.context, _uuid(id)))

    @field_resolver(
        "The caller's organization's datasources, as `GET /v1/organizations/{id}/datasources`."
    )
    async def datasources(
        self,
        info: Info,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        status: str | None = None,
    ) -> DataSourceConnection | None:
        page = await list_datasources(info.context, first=first, after=after, q=q, status=status)
        return DataSourceConnection.of(page)

    @field_resolver(
        "Execution receipts (R11-GQL02), newest first: the caller's own, or every caller's in "
        "the organization for PlatformAdmin and Auditor, optionally of one status. A stale "
        "PENDING receipt is settled from its recorded execution as it is read, so asking for "
        "PENDING lists what is still genuinely unknown. Never rows."
    )
    async def governed_executions(
        self,
        info: Info,
        status: str | None = None,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
    ) -> GovernedExecutionReceiptConnection | None:
        scope = info.context
        if first < 1 or first > scope.limits.max_page_size:
            raise ReadRefused("INVALID_ARGUMENT", "PAGE_SIZE_OUT_OF_RANGE")
        async with scope.lock:
            try:
                page = await list_receipts(
                    scope.session,
                    scope.context,
                    scope.settings,
                    organization_id=scope.organization_id,
                    status=status,
                    first=first,
                    after=after,
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionReceiptConnection(
            nodes=[GovernedExecutionReceipt.of(record) for record in page.items],
            page_info=PageInfo(has_next_page=page.has_next_page, end_cursor=page.end_cursor),
            total_count=page.total,
        )

    @field_resolver(
        "One governed execution receipt (R11-GQL02): the caller's own, or any in the "
        "organization for PlatformAdmin and Auditor. Never rows."
    )
    async def governed_execution(
        self, info: Info, id: strawberry.ID
    ) -> GovernedExecutionReceipt | None:
        scope = info.context
        async with scope.lock:
            try:
                record = await load_receipt(
                    scope.session,
                    scope.context,
                    scope.settings,
                    organization_id=scope.organization_id,
                    record_id=_uuid(id),
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionReceipt.of(record)

    @field_resolver("One table by id, decided as its columns route decides it.")
    async def table(self, info: Info, id: strawberry.ID) -> Table | None:
        return Table.of_row(await get_table(info.context, _uuid(id)))

    @field_resolver(
        "Tables the caller may read. With `datasourceId`, as "
        "`GET /v1/datasources/{id}/tables`; without it, across the caller's organization, "
        "with unreadable datasources removed before counting and paging."
    )
    async def tables(
        self,
        info: Info,
        datasource_id: strawberry.ID | None = None,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        object_type: str | None = None,
        status: str = "ACTIVE",
    ) -> TableConnection | None:
        if datasource_id is not None:
            page = await list_datasource_tables(
                info.context,
                _uuid(datasource_id),
                first=first,
                after=after,
                q=q,
                object_type=object_type,
                status=status,
            )
        else:
            page = await list_organization_tables(
                info.context, first=first, after=after, q=q, object_type=object_type, status=status
            )
        return TableConnection.of(page)


# --- governed execution (R11-GQL02) -------------------------------------------


@strawberry.input(description="One governed execution request (R11-GQL02).")
class ExecuteGovernedToolInput:
    tool_version_id: strawberry.ID = strawberry.field(
        description="A PUBLISHED governed tool version. Nothing else can be executed here."
    )
    idempotency_key: str = strawberry.field(
        description=(
            "8-128 characters of `A-Z a-z 0-9 . _ : -`, chosen by the caller. Sending the same "
            "key again with the same inputs returns the first request's receipt and executes "
            "nothing; the same key with different inputs is refused."
        )
    )
    max_rows: int = strawberry.field(
        description="The row limit, required and explicit; at most the endpoint's execution cap."
    )
    parameters: JSON | None = strawberry.field(
        default=None, description="The tool version's typed parameters, as a JSON object."
    )
    context_product_key: str | None = strawberry.field(
        default=None,
        description=(
            "Execute through this published context product: the tool must be eligible in it "
            "and read only its tables."
        ),
    )


@strawberry.type(
    description=(
        "The durable record of one requested governed execution. Never rows: a receipt is "
        "what can be read again."
    )
)
class GovernedExecutionReceipt:
    id: strawberry.ID
    status: str = strawberry.field(
        description=(
            "PENDING (running, or ended without the platform learning its outcome -- never "
            "retried as a new execution, and settled from the recorded execution once it "
            "cannot still be running), COMPLETED, REJECTED or FAILED (`NOT_STARTED` when "
            "nothing reached the source)."
        )
    )
    tool_version_id: strawberry.ID
    tool_execution_id: strawberry.ID | None
    query_execution_id: strawberry.ID | None
    context_product_version_id: strawberry.ID | None
    row_count: int | None
    outcome_code: str | None = strawberry.field(
        description="A stable refusal or failure code; never a message."
    )
    created_at: datetime
    completed_at: datetime | None

    @classmethod
    def of(cls, record: GovernedExecutionRequest) -> GovernedExecutionReceipt:
        def optional(value: UUID | None) -> strawberry.ID | None:
            return _id(value) if value is not None else None

        return cls(
            id=_id(record.id),
            status=record.status,
            tool_version_id=_id(record.tool_version_id),
            tool_execution_id=optional(record.tool_execution_id),
            query_execution_id=optional(record.query_execution_id),
            context_product_version_id=optional(record.context_product_version_id),
            row_count=record.row_count,
            outcome_code=record.outcome_code,
            created_at=record.created_at,
            completed_at=record.completed_at,
        )


@strawberry.type(description="A page of execution receipts, newest first.")
class GovernedExecutionReceiptConnection:
    nodes: list[GovernedExecutionReceipt]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(
    description=(
        "The rows one execution returned, after the gateway masked them. Present only in the "
        "response of the request that executed; never stored, never replayed."
    )
)
class GovernedExecutionResult:
    columns: list[str]
    rows: JSON = strawberry.field(description="One array per row, in `columns` order.")
    masked_columns: list[str]
    applied_row_limit: int | None


@strawberry.type(description="What an execution mutation answered.")
class GovernedExecutionOutcome:
    receipt: GovernedExecutionReceipt
    replayed: bool = strawberry.field(
        description="True when this key had already been used: nothing executed for this request."
    )
    result: GovernedExecutionResult | None
    quality_gate_action: str | None = strawberry.field(
        description="WARN when an upstream dependency has an open, non-critical quality incident."
    )

    @classmethod
    def of(cls, outcome: ExecutionOutcome) -> GovernedExecutionOutcome:
        response = outcome.response
        result: GovernedExecutionResult | None = None
        gate: str | None = None
        if response is not None:
            execution = response.execution
            columns = list(execution.rows[0].keys()) if execution.rows else []
            result = GovernedExecutionResult(
                columns=columns,
                rows=cast(
                    "JSON", [[row.get(column) for column in columns] for row in execution.rows]
                ),
                masked_columns=list(execution.masked_columns),
                applied_row_limit=execution.applied_row_limit,
            )
            gate = str(response.quality_gate["action"]) if response.quality_gate else None
        return cls(
            receipt=GovernedExecutionReceipt.of(outcome.record),
            replayed=outcome.replayed,
            result=result,
            quality_gate_action=gate,
        )


@strawberry.type(
    description=(
        "Governed execution (R11-GQL02): the only operations that run anything against a "
        "source. One execution field per operation."
    )
)
class Mutation:
    @field_resolver(
        "Execute one approved tool version once for this caller and idempotency key, through "
        "the same governed path as `POST /v1/tool-versions/{version_id}/execute`."
    )
    async def execute_governed_tool(
        self, info: Info, request: ExecuteGovernedToolInput
    ) -> GovernedExecutionOutcome | None:
        scope = info.context
        if not 1 <= request.max_rows <= scope.limits.max_execution_rows:
            raise ReadRefused("INVALID_ARGUMENT", "MAX_ROWS_OUT_OF_RANGE")
        parameters: Any = request.parameters if request.parameters is not None else {}
        if not isinstance(parameters, dict):
            raise ReadRefused("INVALID_ARGUMENT", "PARAMETERS_NOT_AN_OBJECT")
        async with scope.lock:
            try:
                outcome = await execute_governed_tool(
                    scope.session,
                    scope.settings,
                    context=scope.context,
                    organization_id=scope.organization_id,
                    tool_version_id=_uuid(request.tool_version_id),
                    parameters=parameters,
                    max_rows=request.max_rows,
                    context_product_key=request.context_product_key,
                    idempotency_key=request.idempotency_key,
                    correlation_id=get_correlation_id(),
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionOutcome.of(outcome)


def error_code(error: GraphQLError) -> tuple[str, str | None]:
    """The stable (code, reason) for one execution error. Anything that is not a
    deliberate refusal is INTERNAL_ERROR, with no message of its own."""
    original = error.original_error
    if isinstance(original, ReadRefused):
        return original.code, original.reason
    if original is None:
        return "VALIDATION_FAILED", None
    return "INTERNAL_ERROR", None


class _MetadataSchema(strawberry.Schema):
    """Strawberry's schema, with value-free error logging.

    Strawberry's default logs every error with its traceback, and an exception
    raised inside SQLAlchemy carries the statement text and its bound parameters
    -- exactly what INV-6 keeps out of logs. Only the stable code, the exception
    type and the depth of the path are recorded here.
    """

    def process_errors(
        self,
        errors: list[GraphQLError],
        execution_context: ExecutionContext | None = None,
    ) -> None:
        for error in errors:
            code, reason = error_code(error)
            original = error.original_error
            fields = {
                "code": code,
                "reason": reason,
                "path_depth": len(error.path or ()),
                "error_type": type(original).__name__ if original is not None else None,
            }
            if code == "INTERNAL_ERROR":
                _log.error("graphql.resolver_failed", **fields)
            else:
                _log.info("graphql.field_refused", **fields)


def _backstops() -> list[Callable[[], SchemaExtension]]:
    """Strawberry's own limiters, set no tighter than the endpoint's admission
    check. The endpoint refuses first; these guard `metadata_schema.execute`
    against a caller that reaches it by any other route.

    Factories, not instances: strawberry builds a fresh extension per request
    from each, so no extension state is ever shared between two callers.
    """
    limits = DEFAULT_LIMITS
    extensions: list[Callable[[], SchemaExtension]] = [
        lambda: MaxTokensLimiter(max_token_count=limits.max_tokens),
        lambda: MaxAliasesLimiter(max_alias_count=limits.max_aliases),
        lambda: QueryDepthLimiter(max_depth=limits.max_depth),
    ]
    if not limits.allow_introspection:
        extensions.append(DisableIntrospection)
    return extensions


metadata_schema = _MetadataSchema(
    query=Query,
    mutation=Mutation,
    extensions=_backstops(),
    config=StrawberryConfig(disable_field_suggestions=True),
)
