"""The Atlas metadata GraphQL schema (R11-GQL01, design section 13A).

Typed metadata reads -- datasources, tables, columns, constraints, approved
descriptions, context products, lineage, coverage (a context product's, and a
routine's or trigger's parse coverage) and the stored OKF knowledge bundle of a
context product version or a datasource -- with cursor paging. Every resolver is a thin call into
`aida.graphql_reads`, which makes the decision the equivalent REST route makes;
no resolver builds a query of its own, imports a router, or calls over HTTP.

**Queries never reach a source.** No `Query` field reaches a connector or the query
gateway. Governed execution is one explicit mutation, `executeGovernedTool`
(R11-GQL02, `aida.governed_execution`): an approved tool version through the same
path as REST, once per caller-scoped idempotency key. Its rows appear only in that
mutation's response; the `governedExecution` query returns the receipt, which has no
rows by construction. There is no subscription. No type a query can reach
carries a source value either -- no column default, partition bound, view or
routine body, profile statistic or sample row; the metadata types expose what the
REST reads expose and nothing more (`tests/test_graphql_api.py` scans for it).

**Some reads record something.** `contextProductVersion` is the governed read REST's
`GET /v1/context-product-versions/{id}` is: for a consumer it records the consumption
edge, audit and outbox event (channel `GRAPHQL`), exactly as that route does for REST.
`contextProductCoverage` is decided as the compile route decides, and recorded as it
records a compilation less the artifact: an audit event, and for a PUBLISHED version a
consumption edge on channel `GRAPHQL_COVERAGE`. The OKF bundle reads
(`contextProductOkfBundle`, `datasourceOkfBundle` and the fields beneath them) are recorded as
REST's bundle routes record theirs -- an audit event, an outbox event and, for a PUBLISHED
version, a consumption edge -- on channels `GRAPHQL_OKF_*`.

**Refusals are per field.** A field the caller may not read resolves to `null`
with an error whose `extensions.code` is stable and whose message is that code.
Every such field is nullable on purpose, so one forbidden branch does not erase
its permitted siblings.

The published SDL is `Docs/90-reference/graphql-schema.graphql`, regenerated by
`scripts/generate_graphql_schema.py`. `GRAPHQL_SCHEMA_VERSION` is the contract
version: a breaking change to the schema must come with a new version, which
the generator enforces.
"""

from __future__ import annotations

from collections.abc import Callable, Coroutine, Iterator
from datetime import datetime
from enum import Enum
from typing import Any, cast
from uuid import UUID

import strawberry
import structlog
from graphql import GraphQLError
from graphql.validation import NoSchemaIntrospectionCustomRule
from strawberry.extensions import (
    MaxAliasesLimiter,
    MaxTokensLimiter,
    QueryDepthLimiter,
    SchemaExtension,
)
from strawberry.scalars import JSON
from strawberry.schema.config import StrawberryConfig
from strawberry.types import ExecutionContext
from strawberry.types.field import StrawberryField

from aida.governed_execution import (
    ExecutionOutcome,
    ExecutionRefused,
    execute_governed_tool,
    list_receipts,
    load_receipt,
)
from aida.governed_execution_models import GovernedExecutionRequest
from aida.graphql_limits import LIMIT_CEILINGS
from aida.graphql_okf import (
    PRODUCT,
    SOURCE,
    OkfBundleHandle,
    OkfDocumentBody,
    OkfDocumentEntry,
    OkfObjectAnswer,
    OkfObjectItem,
    OkfObjectSource,
    get_okf_bundle,
    list_okf_documents,
    list_okf_findings,
    list_okf_publications,
    read_object_okf,
    read_okf_document,
)
from aida.graphql_reads import (
    ColumnDescription,
    Page,
    ProductCoverage,
    ReadRefused,
    ReadScope,
    TableDescription,
    column_business_description,
    get_context_product_coverage,
    get_context_product_version,
    get_datasource,
    get_lineage_graph,
    get_lineage_impact,
    get_routine_parse_coverage,
    get_table,
    get_trigger_parse_coverage,
    list_columns,
    list_constraints,
    list_context_products,
    list_coverage_items,
    list_datasource_tables,
    list_datasources,
    list_lineage_graph_edges,
    list_lineage_graph_nodes,
    list_lineage_impact_nodes,
    list_organization_tables,
    list_tables,
    referenced_table,
    table_description,
)
from aida.models import MetadataTable
from aida.okf_read_model import BundleSummary, bundle_summary
from aida.schemas import (
    ContextProductRead,
    ContextProductVersionRead,
    DataSourceSummaryRead,
    MetadataColumnRead,
    MetadataConstraintRead,
    MetadataTableRead,
    OkfPublicationRead,
    RoutineParseCoverageRead,
    TriggerParseCoverageRead,
    UnifiedLineageEdgeRead,
    UnifiedLineageGraphRead,
    UnifiedLineageImpactNodeRead,
    UnifiedLineageImpactRead,
    UnifiedLineageNodeRead,
)
from atlas.platform.context import get_correlation_id

__all__ = ["GRAPHQL_SCHEMA_VERSION", "metadata_schema"]

#: The published contract version. Bump it with any breaking change to the SDL;
#: `scripts/generate_graphql_schema.py` refuses to publish a breaking change
#: under an unchanged version.
GRAPHQL_SCHEMA_VERSION = "1"

_log = structlog.get_logger(__name__)

Info = strawberry.Info[ReadScope, None]

_DEFAULT_PAGE = 20

_Resolver = Callable[..., Coroutine[Any, Any, Any]]


def field_resolver(description: str) -> Callable[[_Resolver], StrawberryField]:
    """`@strawberry.field(description=...)`, with a type strict mypy can see.

    Strawberry types its keyword-only `field(...)` overload as returning `Any` (it
    doubles as a plain field default), which makes every decorated resolver
    "untyped" under `mypy --strict`. Passing the resolver positionally selects
    the overload that returns a `StrawberryField` -- the same object the
    decorator form builds. `scripts/generate_surface_control_matrix.py` finds
    resolvers by this decorator's name.
    """

    def decorate(resolver: _Resolver) -> StrawberryField:
        return strawberry.field(resolver, description=description)

    return decorate


def _id(value: UUID) -> strawberry.ID:
    return strawberry.ID(str(value))


def _uuid(value: strawberry.ID) -> UUID:
    try:
        return UUID(str(value))
    except ValueError as exc:
        raise ReadRefused("INVALID_ARGUMENT", "INVALID_ID") from exc


def _optional_uuid(value: strawberry.ID | None) -> UUID | None:
    return None if value is None else _uuid(value)


@strawberry.type(description="Where a page ends and whether another follows it.")
class PageInfo:
    has_next_page: bool
    end_cursor: str | None = strawberry.field(
        description="Pass as `after` for the next page. The same opaque keyset cursor "
        "the equivalent REST route returns as `next_cursor`."
    )


def _page_info(page: Page[Any]) -> PageInfo:
    return PageInfo(has_next_page=page.has_next_page, end_cursor=page.end_cursor)


@strawberry.type(
    description="A registered source system, as `GET /v1/datasources/{id}` returns it."
)
class DataSource:
    id: strawberry.ID
    organization_id: strawberry.ID
    project_id: strawberry.ID
    line_of_business_id: strawberry.ID
    data_domain_id: strawberry.ID
    name: str
    connector_type: str
    dialect: str
    environment: str
    network_zone: str
    status: str
    max_concurrency: int
    created_at: datetime
    updated_at: datetime
    read: strawberry.Private[DataSourceSummaryRead]

    @classmethod
    def of(cls, read: DataSourceSummaryRead) -> DataSource:
        return cls(
            id=_id(read.id),
            organization_id=_id(read.organization_id),
            project_id=_id(read.project_id),
            line_of_business_id=_id(read.line_of_business_id),
            data_domain_id=_id(read.data_domain_id),
            name=read.name,
            connector_type=read.connector_type,
            dialect=read.dialect,
            environment=read.environment,
            network_zone=read.network_zone,
            status=read.status,
            max_concurrency=read.max_concurrency,
            created_at=read.created_at,
            updated_at=read.updated_at,
            read=read,
        )

    @field_resolver("This datasource's tables, as `GET /v1/datasources/{id}/tables`.")
    async def tables(
        self,
        info: Info,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        object_type: str | None = None,
        status: str = "ACTIVE",
    ) -> TableConnection | None:
        page = await list_tables(
            info.context,
            self.read,
            first=first,
            after=after,
            q=q,
            object_type=object_type,
            status=status,
        )
        return TableConnection.of(page)


@strawberry.type(description="A table, view or other relation, as the catalog records it.")
class Table:
    id: strawberry.ID
    datasource_id: strawberry.ID
    schema_id: strawberry.ID
    name: str
    object_type: str
    status: str
    fingerprint: str
    row: strawberry.Private[MetadataTable | None]

    @classmethod
    def of(cls, read: MetadataTableRead, row: MetadataTable | None = None) -> Table:
        return cls(
            id=_id(read.id),
            datasource_id=_id(read.datasource_id),
            schema_id=_id(read.schema_id),
            name=read.name,
            object_type=read.object_type,
            status=read.status,
            fingerprint=read.fingerprint,
            row=row,
        )

    @classmethod
    def of_row(cls, row: MetadataTable) -> Table:
        return cls.of(MetadataTableRead.model_validate(row), row)

    def _subject(self) -> MetadataTable | UUID:
        """What a child read is about. A table reached through a list carries only its
        id; the read service loads it with its siblings and decides it on its own --
        the same table-level decision `GET /v1/tables/{id}/columns` makes."""
        return self.row if self.row is not None else _uuid(self.id)

    @field_resolver("The datasource this table belongs to.")
    async def datasource(self, info: Info) -> DataSource | None:
        return DataSource.of(await get_datasource(info.context, _uuid(self.datasource_id)))

    @field_resolver("Active columns in ordinal order, as `GET /v1/tables/{id}/columns`.")
    async def columns(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> ColumnConnection | None:
        table, page = await list_columns(info.context, self._subject(), first=first, after=after)
        return ColumnConnection.of(page, table)

    @field_resolver(
        "Keys and references, as `GET /v1/tables/{id}/constraints`. A referenced "
        "table is authorized on its own."
    )
    async def constraints(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> ConstraintConnection | None:
        page = await list_constraints(info.context, self._subject(), first=first, after=after)
        return ConstraintConnection.of(page)

    @field_resolver("The approved description, as `GET /v1/tables/{id}/description`.")
    async def description(self, info: Info) -> ApprovedTableDescription | None:
        found = await table_description(info.context, self._subject())
        return ApprovedTableDescription.of(found)


@strawberry.type(description="A column's metadata. Never a value from it.")
class Column:
    id: strawberry.ID
    name: str
    ordinal_position: int
    physical_type: str
    nullable: bool
    classification: str
    classification_source: str
    status: str
    source_description: str | None
    table: strawberry.Private[MetadataTable]

    @classmethod
    def of(cls, read: MetadataColumnRead, table: MetadataTable) -> Column:
        return cls(
            id=_id(read.id),
            name=read.name,
            ordinal_position=read.ordinal_position,
            physical_type=read.physical_type,
            nullable=read.nullable,
            classification=read.classification,
            classification_source=read.classification_source,
            status=read.status,
            source_description=read.source_description,
            table=table,
        )

    @field_resolver(
        "The current approved column description, as "
        "`GET /v1/tables/{id}/column-documentation` reads it."
    )
    async def business_description(self, info: Info) -> ApprovedColumnDescription | None:
        found = await column_business_description(info.context, self.table, _uuid(self.id))
        return ApprovedColumnDescription.of(found) if found is not None else None


@strawberry.type(description="A primary, unique or foreign key.")
class Constraint:
    id: strawberry.ID
    table_id: strawberry.ID
    name: str
    constraint_type: str
    columns: list[str]
    referenced_table_id: strawberry.ID | None
    referenced_columns: list[str]
    status: str
    read: strawberry.Private[MetadataConstraintRead]

    @classmethod
    def of(cls, read: MetadataConstraintRead) -> Constraint:
        return cls(
            id=_id(read.id),
            table_id=_id(read.table_id),
            name=read.name,
            constraint_type=read.constraint_type,
            columns=list(read.columns),
            referenced_table_id=(
                _id(read.referenced_table_id) if read.referenced_table_id is not None else None
            ),
            referenced_columns=list(read.referenced_columns),
            status=read.status,
            read=read,
        )

    @field_resolver("The referenced table, authorized on its own; null when it is absent.")
    async def referenced_table(self, info: Info) -> Table | None:
        row = await referenced_table(info.context, self.read)
        return Table.of_row(row) if row is not None else None


@strawberry.type(description="The approved (maker-checker reviewed) table description.")
class ApprovedTableDescription:
    table_id: strawberry.ID
    name: str
    source_description: str | None
    readme: str | None
    readme_version: int | None
    approved_by: str | None
    approved_at: datetime | None
    withdrawn_readme: str | None

    @classmethod
    def of(cls, found: TableDescription) -> ApprovedTableDescription:
        return cls(
            table_id=_id(found.table_id),
            name=found.name,
            source_description=found.source_description,
            readme=found.readme,
            readme_version=found.readme_version,
            approved_by=found.approved_by,
            approved_at=found.approved_at,
            withdrawn_readme=found.withdrawn_readme,
        )


@strawberry.type(description="The approved (maker-checker reviewed) column description.")
class ApprovedColumnDescription:
    description: str
    version: int
    approved_by: str | None
    approved_at: datetime | None

    @classmethod
    def of(cls, found: ColumnDescription) -> ApprovedColumnDescription:
        return cls(
            description=found.description,
            version=found.version,
            approved_by=found.approved_by,
            approved_at=found.approved_at,
        )


@strawberry.type(description="A page of datasources.")
class DataSourceConnection:
    nodes: list[DataSource]
    page_info: PageInfo
    total_count: int | None = strawberry.field(
        description="Computed on the first page only (no `after`), as REST computes `total`."
    )

    @classmethod
    def of(cls, page: Page[DataSourceSummaryRead]) -> DataSourceConnection:
        return cls(
            nodes=[DataSource.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of tables.")
class TableConnection:
    nodes: list[Table]
    page_info: PageInfo
    total_count: int | None = strawberry.field(
        description="Computed on the first page only, and only over what the caller may read."
    )

    @classmethod
    def of(cls, page: Page[MetadataTableRead]) -> TableConnection:
        return cls(
            nodes=[Table.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of columns.")
class ColumnConnection:
    nodes: list[Column]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[MetadataColumnRead], table: MetadataTable) -> ColumnConnection:
        return cls(
            nodes=[Column.of(item, table) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of constraints.")
class ConstraintConnection:
    nodes: list[Constraint]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[MetadataConstraintRead]) -> ConstraintConnection:
        return cls(
            nodes=[Constraint.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(
    description=(
        "One version of a context product, as `GET /v1/context-product-versions/{id}` returns it: "
        "what it names and who may ask through it. Reading it through `contextProductVersion` "
        "is a governed consumption, recorded as REST records its own."
    )
)
class ContextProductVersion:
    id: strawberry.ID
    product_id: strawberry.ID
    product_key: str
    version: int
    status: str
    name: str
    description: str
    purpose: str
    owner_type: str
    owner_principal: str
    table_ids: list[strawberry.ID]
    eligible_tool_version_ids: list[strawberry.ID]
    routine_ids: list[strawberry.ID]
    allowed_consumer_roles: list[str]
    lineage_depth: int
    fingerprint: str
    published_at: datetime | None
    support_window_ends_at: datetime | None
    superseded_by_version_id: strawberry.ID | None

    @classmethod
    def of(cls, read: ContextProductVersionRead) -> ContextProductVersion:
        return cls(
            id=_id(read.id),
            product_id=_id(read.product_id),
            product_key=read.product_key,
            version=read.version,
            status=read.status,
            name=read.name,
            description=read.description,
            purpose=read.purpose,
            owner_type=read.owner_type,
            owner_principal=read.owner_principal,
            table_ids=[_id(value) for value in read.table_ids],
            eligible_tool_version_ids=[_id(value) for value in read.eligible_tool_version_ids],
            routine_ids=[_id(value) for value in read.routine_ids],
            allowed_consumer_roles=list(read.allowed_consumer_roles),
            lineage_depth=read.lineage_depth,
            fingerprint=read.fingerprint,
            published_at=read.published_at,
            support_window_ends_at=read.support_window_ends_at,
            superseded_by_version_id=(
                _id(read.superseded_by_version_id) if read.superseded_by_version_id else None
            ),
        )


@strawberry.type(
    description="A context product in a project listing, with the version that listing shows."
)
class ContextProduct:
    id: strawberry.ID
    project_id: strawberry.ID
    product_key: str
    lifecycle_status: str
    latest_version: ContextProductVersion

    @classmethod
    def of(cls, read: ContextProductRead) -> ContextProduct:
        return cls(
            id=_id(read.id),
            project_id=_id(read.project_id),
            product_key=read.product_key,
            lifecycle_status=read.lifecycle_status,
            latest_version=ContextProductVersion.of(read.latest_version),
        )


@strawberry.type(description="A page of context products, in `productKey` order.")
class ContextProductConnection:
    nodes: list[ContextProduct]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[ContextProductRead]) -> ContextProductConnection:
        return cls(
            nodes=[ContextProduct.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


# --- unified lineage (R11-GQL01) ----------------------------------------------


@strawberry.enum(
    description="Which relationship suggestions a lineage graph folds in: the unified-lineage "
    "graph route's `suggestion_status`."
)
class LineageSuggestionStatus(Enum):
    ALL = "ALL"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


@strawberry.type(
    description="A node an impact traversal reached, as "
    "`GET /v1/datasources/{id}/unified-lineage/impact/{node_id}` returns it."
)
class LineageImpactNode:
    node_id: str
    node_kind: str
    label: str
    qualified_name: str
    depth: int = strawberry.field(description="Hops from the focus node.")
    contributing_edge_sources: list[str]
    quality_state: str = strawberry.field(
        description="PASSING, STALE, UNKNOWN or INCIDENT_OPEN for a table -- the Catalog's "
        "own states -- and NOT_APPLICABLE for any other node."
    )

    @classmethod
    def of(cls, read: UnifiedLineageImpactNodeRead) -> LineageImpactNode:
        return cls(
            node_id=read.node_id,
            node_kind=read.node_kind,
            label=read.label,
            qualified_name=read.qualified_name,
            depth=read.depth,
            contributing_edge_sources=list(read.contributing_edge_sources),
            quality_state=read.quality_state,
        )


@strawberry.type(
    description="A page of one direction of an impact traversal, in the traversal's own "
    "(depth, nodeId) order."
)
class LineageImpactNodeConnection:
    nodes: list[LineageImpactNode]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[UnifiedLineageImpactNodeRead]) -> LineageImpactNodeConnection:
        return cls(
            nodes=[LineageImpactNode.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(
    description=(
        "Transitive upstream and downstream impact from one lineage node, as "
        "`GET /v1/datasources/{id}/unified-lineage/impact/{node_id}` computes it: one bounded "
        "traversal across every merged edge kind, with REST's truncation flags."
    )
)
class LineageImpact:
    datasource_id: strawberry.ID
    focus_node_id: str
    focus_node_kind: str
    focus_label: str
    requested_depth: int
    node_limit: int
    upstream_truncated: bool
    downstream_truncated: bool
    read: strawberry.Private[UnifiedLineageImpactRead]

    @classmethod
    def of(cls, read: UnifiedLineageImpactRead) -> LineageImpact:
        return cls(
            datasource_id=_id(read.datasource_id),
            focus_node_id=read.focus_node_id,
            focus_node_kind=read.focus_node_kind,
            focus_label=read.focus_label,
            requested_depth=read.requested_depth,
            node_limit=read.node_limit,
            upstream_truncated=read.upstream_truncated,
            downstream_truncated=read.downstream_truncated,
            read=read,
        )

    @field_resolver("What the focus node depends on, a page at a time.")
    async def upstream(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> LineageImpactNodeConnection | None:
        page = await list_lineage_impact_nodes(
            info.context, self.read, upstream=True, first=first, after=after
        )
        return LineageImpactNodeConnection.of(page)

    @field_resolver("What depends on the focus node, a page at a time.")
    async def downstream(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> LineageImpactNodeConnection | None:
        page = await list_lineage_impact_nodes(
            info.context, self.read, upstream=False, first=first, after=after
        )
        return LineageImpactNodeConnection.of(page)


@strawberry.type(
    description="A node of the merged lineage graph: a catalog table, or a synthetic node for "
    "a dbt resource, OpenLineage dataset or BI report not matched to one."
)
class LineageNode:
    id: str
    node_kind: str
    label: str
    qualified_name: str
    matched_table_id: strawberry.ID | None
    resolved: bool
    inbound_edge_count: int
    outbound_edge_count: int

    @classmethod
    def of(cls, read: UnifiedLineageNodeRead) -> LineageNode:
        return cls(
            id=read.id,
            node_kind=read.node_kind,
            label=read.label,
            qualified_name=read.qualified_name,
            matched_table_id=_id(read.matched_table_id) if read.matched_table_id else None,
            resolved=read.resolved,
            inbound_edge_count=read.inbound_edge_count,
            outbound_edge_count=read.outbound_edge_count,
        )


@strawberry.type(description="A typed edge of the merged lineage graph.")
class LineageEdge:
    id: str
    edge_source: str
    source_node_id: str
    target_node_id: str
    source_label: str
    target_label: str
    status: str
    confidence: float
    source_columns: list[str]
    target_columns: list[str]
    evidence: JSON = strawberry.field(
        description="What establishes the edge, exactly as the REST route serves it: never a "
        "value from the source, and never an approved join's recorded validation."
    )

    @classmethod
    def of(cls, read: UnifiedLineageEdgeRead) -> LineageEdge:
        return cls(
            id=read.id,
            edge_source=read.edge_source,
            source_node_id=read.source_node_id,
            target_node_id=read.target_node_id,
            source_label=read.source_label,
            target_label=read.target_label,
            status=read.status,
            confidence=read.confidence,
            source_columns=list(read.source_columns),
            target_columns=list(read.target_columns),
            # The route's own serializer (R11-FP06) decides what evidence leaves.
            evidence=cast("JSON", read.model_dump(mode="json")["evidence"]),
        )


@strawberry.type(description="A page of lineage nodes, in `qualifiedName` order.")
class LineageNodeConnection:
    nodes: list[LineageNode]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[UnifiedLineageNodeRead]) -> LineageNodeConnection:
        return cls(
            nodes=[LineageNode.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="A page of lineage edges, in edge id order.")
class LineageEdgeConnection:
    nodes: list[LineageEdge]
    page_info: PageInfo
    total_count: int | None

    @classmethod
    def of(cls, page: Page[UnifiedLineageEdgeRead]) -> LineageEdgeConnection:
        return cls(
            nodes=[LineageEdge.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(
    description=(
        "A datasource's merged lineage graph -- declared keys, reviewed relationships, dbt, "
        "OpenLineage, view and procedure definitions and BI reports -- as "
        "`GET /v1/datasources/{id}/unified-lineage/graph` builds it, with its bounds and "
        "whether they cut anything."
    )
)
class LineageGraph:
    datasource_id: strawberry.ID
    counts_by_source: JSON
    returned_node_count: int
    returned_edge_count: int
    node_limit: int
    edge_limit: int
    truncated: bool
    truncation_reasons: list[str]
    read: strawberry.Private[UnifiedLineageGraphRead]

    @classmethod
    def of(cls, read: UnifiedLineageGraphRead) -> LineageGraph:
        return cls(
            datasource_id=_id(read.datasource_id),
            counts_by_source=cast("JSON", dict(read.counts_by_source)),
            returned_node_count=read.returned_node_count,
            returned_edge_count=read.returned_edge_count,
            node_limit=read.node_limit,
            edge_limit=read.edge_limit,
            truncated=read.truncated,
            truncation_reasons=list(read.truncation_reasons),
            read=read,
        )

    @field_resolver("The graph's nodes, a page at a time.")
    async def nodes(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> LineageNodeConnection | None:
        page = await list_lineage_graph_nodes(info.context, self.read, first=first, after=after)
        return LineageNodeConnection.of(page)

    @field_resolver("The graph's edges, a page at a time.")
    async def edges(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> LineageEdgeConnection | None:
        page = await list_lineage_graph_edges(info.context, self.read, first=first, after=after)
        return LineageEdgeConnection.of(page)


# --- coverage (R11-GQL01) -------------------------------------------------------


def _ids(values: list[Any]) -> list[strawberry.ID]:
    return [strawberry.ID(str(value)) for value in values]


def _optional_id(value: Any) -> strawberry.ID | None:
    return strawberry.ID(str(value)) if value is not None else None


@strawberry.type(
    description="A routine a context product names, and how completely Atlas understands it -- "
    "an entry of the compiled product's `coverage.routines`. Never the body."
)
class CoveredRoutine:
    id: strawberry.ID
    qualified_name: str
    routine_type: str
    signature: str
    status: str
    definition_available: bool = strawberry.field(
        description="Whether the redacted, screened body would be released on request."
    )
    lineage: str = strawberry.field(description="ACTIVE, PROPOSED or NONE.")
    fully_parsed: bool
    reads_table_ids: list[strawberry.ID] = strawberry.field(
        description="Only tables the product itself covers; nothing outside it is named or "
        "counted."
    )
    writes_table_ids: list[strawberry.ID]
    definition_digest: str | None = strawberry.field(
        description="SHA-256 of the stored value-free body; null when none is stored."
    )
    description: str | None = strawberry.field(
        description="The approved description, and only an approved one."
    )
    description_state: str = strawberry.field(
        description="APPROVED, PROPOSED, WITHDRAWN or NONE."
    )

    @classmethod
    def of(cls, entry: dict[str, Any]) -> CoveredRoutine:
        return cls(
            id=strawberry.ID(str(entry["id"])),
            qualified_name=entry["qualified_name"],
            routine_type=entry["routine_type"],
            signature=entry["signature"],
            status=entry["status"],
            definition_available=entry["definition_available"],
            lineage=entry["lineage"],
            fully_parsed=entry["fully_parsed"],
            reads_table_ids=_ids(entry["reads_table_ids"]),
            writes_table_ids=_ids(entry["writes_table_ids"]),
            definition_digest=entry["definition_digest"],
            description=entry["description"],
            description_state=entry["description_state"],
        )


@strawberry.type(
    description="A view or materialized view among a context product's tables, and what Atlas "
    "holds of its definition -- an entry of `coverage.views`."
)
class CoveredView:
    table_id: strawberry.ID
    object_type: str
    status: str
    definition_available: bool
    truncated: bool
    lineage: str
    definition_digest: str | None

    @classmethod
    def of(cls, entry: dict[str, Any]) -> CoveredView:
        return cls(
            table_id=strawberry.ID(str(entry["table_id"])),
            object_type=entry["object_type"],
            status=entry["status"],
            definition_available=entry["definition_available"],
            truncated=entry["truncated"],
            lineage=entry["lineage"],
            definition_digest=entry["definition_digest"],
        )


@strawberry.type(
    description="An ontology, semantic model or glossary term version a context product pins, "
    "whether it still stands, and what it speaks about within the product -- an entry of "
    "`coverage.meaning`."
)
class CoveredMeaning:
    kind: str = strawberry.field(description="ONTOLOGY, SEMANTIC_MODEL or GLOSSARY_TERM.")
    version_id: strawberry.ID
    key: str | None
    version: int
    status: str
    current: bool
    table_ids: list[strawberry.ID]
    routine_ids: list[strawberry.ID]

    @classmethod
    def of(cls, entry: dict[str, Any]) -> CoveredMeaning:
        return cls(
            kind=entry["kind"],
            version_id=strawberry.ID(str(entry["version_id"])),
            key=entry["key"],
            version=entry["version"],
            status=entry["status"],
            current=entry["current"],
            table_ids=_ids(entry["table_ids"]),
            routine_ids=_ids(entry["routine_ids"]),
        )


@strawberry.type(
    description="Something a published context product covers that moved after it was "
    "published -- an entry of `coverage.changed_since_published`. Its presence is the product "
    "saying it is stale."
)
class CoverageChange:
    subject_kind: str
    subject_id: strawberry.ID
    change: str
    change_class: str | None

    @classmethod
    def of(cls, entry: dict[str, Any]) -> CoverageChange:
        return cls(
            subject_kind=entry["subject_kind"],
            subject_id=strawberry.ID(str(entry["subject_id"])),
            change=entry["change"],
            change_class=entry["change_class"],
        )


@strawberry.type(
    description="When a source behind a context product was last read, and last read in full "
    "-- an entry of the compile route's `generated_from.source_freshness`."
)
class SourceFreshness:
    datasource_id: strawberry.ID
    table_ids: list[strawberry.ID]
    last_scan_completed_at: str | None = strawberry.field(
        description="ISO-8601, exactly as the compile route renders it."
    )
    last_full_scan_completed_at: str | None

    @classmethod
    def of(cls, entry: dict[str, Any]) -> SourceFreshness:
        return cls(
            datasource_id=strawberry.ID(str(entry["datasource_id"])),
            table_ids=_ids(entry["table_ids"]),
            last_scan_completed_at=entry["last_scan_completed_at"],
            last_full_scan_completed_at=entry["last_full_scan_completed_at"],
        )


@strawberry.type(description="A page of covered routines, in id order.")
class CoveredRoutineConnection:
    nodes: list[CoveredRoutine]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of covered views, in table id order.")
class CoveredViewConnection:
    nodes: list[CoveredView]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of pinned meaning, in (kind, versionId) order.")
class CoveredMeaningConnection:
    nodes: list[CoveredMeaning]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of changes since publication, in (kind, id, change) order.")
class CoverageChangeConnection:
    nodes: list[CoverageChange]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of source freshness, in datasource id order.")
class SourceFreshnessConnection:
    nodes: list[SourceFreshness]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(
    description=(
        "What a context product version covers and how completely -- the compiled product's "
        "`coverage` section and the freshness beside it, as "
        "`GET /v1/context-product-versions/{id}/compile` resolves them, decided as that route "
        "decides. Reading it is recorded as that route records a compilation: an audit event, "
        "and for a PUBLISHED version a consumption on channel GRAPHQL_COVERAGE."
    )
)
class ContextProductCoverage:
    version_id: strawberry.ID
    product_key: str
    version: int
    status: str
    read: strawberry.Private[ProductCoverage]

    @classmethod
    def of(cls, read: ProductCoverage) -> ContextProductCoverage:
        return cls(
            version_id=_id(read.version_id),
            product_key=read.product_key,
            version=read.version,
            status=read.status,
            read=read,
        )

    @field_resolver("The routines the version names, a page at a time.")
    async def routines(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> CoveredRoutineConnection | None:
        page = await list_coverage_items(
            info.context, self.read, "routines", first=first, after=after
        )
        return CoveredRoutineConnection(
            nodes=[CoveredRoutine.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver("The views and materialized views among the version's tables.")
    async def views(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> CoveredViewConnection | None:
        page = await list_coverage_items(info.context, self.read, "views", first=first, after=after)
        return CoveredViewConnection(
            nodes=[CoveredView.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver("The ontology, semantic model and glossary term versions the version pins.")
    async def meaning(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> CoveredMeaningConnection | None:
        page = await list_coverage_items(
            info.context, self.read, "meaning", first=first, after=after
        )
        return CoveredMeaningConnection(
            nodes=[CoveredMeaning.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver("What the version covers that moved after it was published.")
    async def changed_since_published(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> CoverageChangeConnection | None:
        page = await list_coverage_items(
            info.context, self.read, "changed_since_published", first=first, after=after
        )
        return CoverageChangeConnection(
            nodes=[CoverageChange.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver("When each source behind the version's tables was last read.")
    async def source_freshness(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> SourceFreshnessConnection | None:
        page = await list_coverage_items(
            info.context, self.read, "source_freshness", first=first, after=after
        )
        return SourceFreshnessConnection(
            nodes=[SourceFreshness.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(
    description="How completely one routine's body was understood, as last measured -- "
    "`GET /v1/datasources/{id}/procedures/{routine_id}/parse-coverage`."
)
class RoutineParseCoverage:
    routine_id: strawberry.ID
    state: str = strawberry.field(description="SUPPORTED, PARTIAL or UNAVAILABLE.")
    parse_completed: bool
    is_read_only: bool
    statement_count: int
    unparsed_statement_count: int
    unparsed_reason_codes: list[str]
    dialect: str
    confidence: str
    source_mapping_granularity: str
    parsed_at: datetime
    member_attribution: str | None
    member_fallback_reason: str | None

    @classmethod
    def of(cls, read: RoutineParseCoverageRead) -> RoutineParseCoverage:
        return cls(
            routine_id=_id(read.routine_id),
            state=read.state,
            parse_completed=read.parse_completed,
            is_read_only=read.is_read_only,
            statement_count=read.statement_count,
            unparsed_statement_count=read.unparsed_statement_count,
            unparsed_reason_codes=list(read.unparsed_reason_codes),
            dialect=read.dialect,
            confidence=read.confidence,
            source_mapping_granularity=read.source_mapping_granularity,
            parsed_at=read.parsed_at,
            member_attribution=read.member_attribution,
            member_fallback_reason=read.member_fallback_reason,
        )


@strawberry.type(
    description="How completely one trigger's body was understood, as last measured -- "
    "`GET /v1/datasources/{id}/triggers/{trigger_id}/parse-coverage`."
)
class TriggerParseCoverage:
    trigger_id: strawberry.ID
    routine_id: strawberry.ID | None = strawberry.field(
        description="The routine the body was read from (a PostgreSQL trigger's function)."
    )
    state: str
    parse_completed: bool
    is_read_only: bool
    statement_count: int
    unparsed_statement_count: int
    unparsed_reason_codes: list[str]
    dialect: str
    confidence: str
    source_mapping_granularity: str
    parsed_at: datetime

    @classmethod
    def of(cls, read: TriggerParseCoverageRead) -> TriggerParseCoverage:
        return cls(
            trigger_id=_id(read.trigger_id),
            routine_id=_optional_id(read.routine_id),
            state=read.state,
            parse_completed=read.parse_completed,
            is_read_only=read.is_read_only,
            statement_count=read.statement_count,
            unparsed_statement_count=read.unparsed_statement_count,
            unparsed_reason_codes=list(read.unparsed_reason_codes),
            dialect=read.dialect,
            confidence=read.confidence,
            source_mapping_granularity=read.source_mapping_granularity,
            parsed_at=read.parsed_at,
        )


# --- stored OKF bundles (R11-GQL01, R11-OKF02) -----------------------------------------


@strawberry.enum(description="Which kind of stored bundle a read is of.")
class OkfBundleScope(Enum):
    CONTEXT_PRODUCT_VERSION = "CONTEXT_PRODUCT_VERSION"
    DATASOURCE = "DATASOURCE"


@strawberry.enum(
    description="What a stored document is, by where the renderer put it. A pure function of "
    "the path -- no document is opened to say."
)
class OkfDocumentKind(Enum):
    BUNDLE_INDEX = "BUNDLE_INDEX"
    SOURCE_INDEX = "SOURCE_INDEX"
    SCHEMA_INDEX = "SCHEMA_INDEX"
    SCHEMA_INDEX_PAGE = "SCHEMA_INDEX_PAGE"
    TABLE = "TABLE"
    VIEW = "VIEW"
    COLUMN_SET = "COLUMN_SET"
    ROUTINE = "ROUTINE"
    PACKAGE = "PACKAGE"
    CONCEPT_INDEX = "CONCEPT_INDEX"
    CONCEPT = "CONCEPT"
    TOOL_INDEX = "TOOL_INDEX"
    TOOL = "TOOL"
    LOG = "LOG"
    OTHER = "OTHER"


@strawberry.type(description="What a bundle's manifest counts, by kind of thing it holds.")
class OkfBundleCounts:
    sources: int
    schemas: int
    tables: int
    views: int
    routines: int
    packages: int
    concepts: int
    tools: int
    documents: int

    @classmethod
    def of(cls, counts: dict[str, int]) -> OkfBundleCounts:
        return cls(
            sources=counts.get("sources", 0),
            schemas=counts.get("schemas", 0),
            tables=counts.get("tables", 0),
            views=counts.get("views", 0),
            routines=counts.get("routines", 0),
            packages=counts.get("packages", 0),
            concepts=counts.get("concepts", 0),
            tools=counts.get("tools", 0),
            documents=counts.get("documents", 0),
        )


@strawberry.type(
    description="One stored, immutable publication of a bundle in the reader's own lineage. "
    "`publicationId` is the snapshot identity a caller pins: the manifest it inspected and any "
    "document it reads are the same bytes when both name it. `renderedCount` documents were "
    "rendered by this publication; `carriedCount` kept the prior publication's stored bytes "
    "without being rendered at all."
)
class OkfPublication:
    publication_id: strawberry.ID
    sequence: int
    trigger: str
    captured_at: datetime
    is_current: bool
    bundle_content_digest: str
    content_snapshot_digest: str
    document_count: int
    rendered_count: int
    carried_count: int
    valid: bool
    added_count: int = strawberry.field(description="Documents this publication added.")
    changed_count: int = strawberry.field(description="Documents whose bytes it changed.")
    removed_count: int = strawberry.field(description="Documents it removed.")
    changed_subjects: int = strawberry.field(
        description="Identity keys whose frozen facts moved."
    )
    marked_subjects: int = strawberry.field(
        description="Catalog subjects whose change marks triggered the rebuild."
    )
    full_render: bool

    @classmethod
    def of(cls, read: OkfPublicationRead) -> OkfPublication:
        return cls(
            publication_id=_id(read.publication_id),
            sequence=read.sequence,
            trigger=read.trigger,
            captured_at=read.captured_at,
            is_current=read.is_current,
            bundle_content_digest=read.bundle_content_digest,
            content_snapshot_digest=read.content_snapshot_digest,
            document_count=read.document_count,
            rendered_count=read.rendered_count,
            carried_count=read.carried_count,
            valid=read.valid,
            added_count=len(read.changes.added),
            changed_count=len(read.changes.changed),
            removed_count=len(read.changes.removed),
            changed_subjects=read.changes.changed_subjects,
            marked_subjects=read.changes.marked_subjects,
            full_render=read.changes.full_render,
        )


@strawberry.type(
    description="One finding of the Atlas publish policy for a publication. `code` is its "
    "machine code; `detail` the path and target it names, where it names any."
)
class OkfFinding:
    text: str
    code: str
    detail: str | None

    @classmethod
    def of(cls, text: str) -> OkfFinding:
        code, separator, detail = text.partition(":")
        return cls(text=text, code=code, detail=detail if separator else None)


@strawberry.type(
    description="One stored document as a list shows it: where it sits, what it is, the digest "
    "of its bytes and how to cite it. Never its text -- read one document by path with "
    "`OkfBundle.document`."
)
class OkfDocumentSummary:
    publication_id: strawberry.ID
    publication_sequence: int
    path: str = strawberry.field(description="The bundle's own opaque, safe path.")
    kind: OkfDocumentKind
    citation: str = strawberry.field(
        description="`okf:<publicationId>:<path>@<sha256>` -- the reference an answer carries to "
        "cite exactly this document: the publication it was read from, its path and the digest "
        "of its bytes."
    )
    sha256: str
    bytes: int
    rendered_in_sequence: int = strawberry.field(
        description="The publication that first rendered these exact bytes: earlier than "
        "`publicationSequence` when a rebuild carried the document forward unchanged."
    )
    subject_key: str | None = strawberry.field(
        description="The identity key of the object, concept or tool the document is about; "
        "null for an index or a log."
    )

    @classmethod
    def of(cls, entry: OkfDocumentEntry) -> OkfDocumentSummary:
        return cls(
            publication_id=_id(entry.publication_id),
            publication_sequence=entry.publication_sequence,
            path=entry.path,
            kind=OkfDocumentKind(entry.kind),
            citation=entry.citation,
            sha256=entry.sha256,
            bytes=entry.bytes,
            rendered_in_sequence=entry.rendered_in_sequence,
            subject_key=entry.subject_key,
        )


@strawberry.type(
    description="One stored document with its exact stored text, as "
    "`GET .../okf-bundle/document` returns it: the Markdown a reader of the downloaded archive "
    "finds at `path`, whose digest is `sha256`."
)
class OkfDocument:
    publication_id: strawberry.ID
    publication_sequence: int
    path: str
    kind: OkfDocumentKind
    citation: str
    sha256: str
    bytes: int
    rendered_in_sequence: int
    subject_key: str | None
    text: str

    @classmethod
    def of(cls, body: OkfDocumentBody) -> OkfDocument:
        entry = body.entry
        return cls(
            publication_id=_id(entry.publication_id),
            publication_sequence=entry.publication_sequence,
            path=entry.path,
            kind=OkfDocumentKind(entry.kind),
            citation=entry.citation,
            sha256=entry.sha256,
            bytes=entry.bytes,
            rendered_in_sequence=entry.rendered_in_sequence,
            subject_key=entry.subject_key,
            text=body.text,
        )


@strawberry.type(
    description="One context product bundle's document about a catalog object (R11-OKF02)."
)
class OkfObjectKnowledgeItem:
    product_key: str
    product_version: int
    product_name: str
    publication: OkfPublication
    document: OkfDocument

    @classmethod
    def of(cls, item: OkfObjectItem) -> OkfObjectKnowledgeItem:
        return cls(
            product_key=item.product_key,
            product_version=item.product_version,
            product_name=item.product_name,
            publication=OkfPublication.of(item.publication),
            document=OkfDocument.of(item.document),
        )


@strawberry.type(
    description="The object's own datasource bundle's answer, read only when no product "
    "bundle holds it: DOCUMENT, NOT_IN_BUNDLE (counts nothing) or REFUSED (the bare reason "
    "code, and no bundle named)."
)
class OkfObjectSourceKnowledge:
    state: str
    reason: str | None
    datasource_id: strawberry.ID | None
    publication: OkfPublication | None
    document: OkfDocument | None

    @classmethod
    def of(cls, source: OkfObjectSource) -> OkfObjectSourceKnowledge:
        return cls(
            state=source.state,
            reason=source.reason,
            datasource_id=_id(source.datasource_id) if source.datasource_id else None,
            publication=OkfPublication.of(source.publication) if source.publication else None,
            document=OkfDocument.of(source.document) if source.document else None,
        )


@strawberry.type(
    description="The stored knowledge about one catalog object, as "
    "`GET /v1/metadata/tables/{id}/okf-knowledge` reads it. `items` holds at most one entry "
    "per context product whose bundle the caller may read."
)
class OkfObjectKnowledge:
    table_id: strawberry.ID
    items: list[OkfObjectKnowledgeItem]
    source: OkfObjectSourceKnowledge | None

    @classmethod
    def of(cls, answer: OkfObjectAnswer) -> OkfObjectKnowledge:
        return cls(
            table_id=_id(answer.table_id),
            items=[OkfObjectKnowledgeItem.of(item) for item in answer.items],
            source=OkfObjectSourceKnowledge.of(answer.source) if answer.source else None,
        )


@strawberry.type(description="A page of stored documents, in path order.")
class OkfDocumentSummaryConnection:
    nodes: list[OkfDocumentSummary]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of stored publications, newest first.")
class OkfPublicationConnection:
    nodes: list[OkfPublication]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(description="A page of publish-policy findings, in text order.")
class OkfFindingConnection:
    nodes: list[OkfFinding]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(
    description="A stored OKF knowledge bundle -- a context product version's approved "
    "references, or one datasource's discovered objects as this caller may read them -- as "
    "`GET .../okf-bundle` describes it: the manifest's summary, the counts, the publication "
    "read and the publish policy's verdict. The documents, the history and the findings are "
    "connections beneath it; a document's text is read one path at a time. Every object in it "
    "is one this caller's own authorization admitted; nothing else is named or counted."
)
class OkfBundle:
    scope: OkfBundleScope
    context_product_version_id: strawberry.ID | None = strawberry.field(
        description="The version a product bundle is of; null for a datasource's."
    )
    product_key: str | None
    product_version: int | None
    datasource_id: strawberry.ID | None = strawberry.field(
        description="The datasource a source bundle is of; null for a product's."
    )
    okf_version: str
    spec_revision: str
    spec_conformance: str = strawberry.field(
        description="Exactly what was tested against the pinned specification -- never a "
        "certification."
    )
    profile: str
    content_snapshot_digest: str
    bundle_content_digest: str
    scope_digest: str
    document_count: int
    valid: bool = strawberry.field(
        description="Whether the bundle satisfies the Atlas publish policy -- an Atlas policy "
        "answer, not a statement that the bundle is unreadable. A download of an invalid "
        "bundle is refused; this read is not."
    )
    finding_count: int
    counts: OkfBundleCounts
    publication: OkfPublication
    validated_at: datetime = strawberry.field(
        description="When the caller's lineage was last confirmed current, which may be later "
        "than the publication: a no-op revalidation confirms without publishing."
    )
    read: strawberry.Private[OkfBundleHandle]

    @classmethod
    def of(cls, handle: OkfBundleHandle) -> OkfBundle:
        summary: BundleSummary = bundle_summary(handle.stored)
        product = handle.target == PRODUCT
        return cls(
            scope=(
                OkfBundleScope.CONTEXT_PRODUCT_VERSION if product else OkfBundleScope.DATASOURCE
            ),
            context_product_version_id=_id(handle.target_id) if product else None,
            product_key=handle.product_key,
            product_version=handle.product_version,
            datasource_id=None if product else _id(handle.target_id),
            okf_version=summary.okf_version,
            spec_revision=summary.spec_revision,
            spec_conformance=summary.spec_conformance,
            profile=summary.profile,
            content_snapshot_digest=summary.content_snapshot_digest,
            bundle_content_digest=summary.bundle_content_digest,
            scope_digest=summary.scope_digest,
            document_count=summary.document_count,
            valid=summary.valid,
            finding_count=len(summary.findings),
            counts=OkfBundleCounts.of(summary.counts),
            publication=OkfPublication.of(summary.publication),
            validated_at=summary.validated_at,
            read=handle,
        )

    @field_resolver(
        "This bundle's documents, a page at a time in path order, without their text. Each "
        "carries its path, kind, digest, size and citation."
    )
    async def documents(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> OkfDocumentSummaryConnection | None:
        page = await list_okf_documents(info.context, self.read, first=first, after=after)
        return OkfDocumentSummaryConnection(
            nodes=[OkfDocumentSummary.of(entry) for entry in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver(
        "One document with its exact stored text, as `GET .../okf-bundle/document?path=` reads "
        "it: looked up only among the stored rows of this publication, so a path that is not "
        "in the bundle reads as NOT_FOUND. Recorded, with the path."
    )
    async def document(self, info: Info, path: str) -> OkfDocument | None:
        return OkfDocument.of(await read_okf_document(info.context, self.read, path=path))

    @field_resolver(
        "The caller's own lineage of stored publications, newest first, as "
        "`GET .../okf-bundle/publications` lists it: what changed, when, and why. A "
        "publication built under another authority is neither listed nor counted."
    )
    async def publications(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> OkfPublicationConnection | None:
        page = await list_okf_publications(info.context, self.read, first=first, after=after)
        return OkfPublicationConnection(
            nodes=[OkfPublication.of(item) for item in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )

    @field_resolver("The publish policy's findings for this publication, a page at a time.")
    async def findings(
        self, info: Info, first: int = _DEFAULT_PAGE, after: str | None = None
    ) -> OkfFindingConnection | None:
        page = await list_okf_findings(info.context, self.read, first=first, after=after)
        return OkfFindingConnection(
            nodes=[OkfFinding.of(text) for text in page.items],
            page_info=_page_info(page),
            total_count=page.total,
        )


@strawberry.type(description="Metadata reads. Nothing here executes against a source.")
class Query:
    @field_resolver("One datasource by id, as `GET /v1/datasources/{id}`.")
    async def datasource(self, info: Info, id: strawberry.ID) -> DataSource | None:
        return DataSource.of(await get_datasource(info.context, _uuid(id)))

    @field_resolver(
        "The caller's organization's datasources, as `GET /v1/organizations/{id}/datasources`."
    )
    async def datasources(
        self,
        info: Info,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        status: str | None = None,
    ) -> DataSourceConnection | None:
        page = await list_datasources(info.context, first=first, after=after, q=q, status=status)
        return DataSourceConnection.of(page)

    @field_resolver(
        "Execution receipts (R11-GQL02), newest first: the caller's own, or every caller's in "
        "the organization for PlatformAdmin and Auditor, optionally of one status. A stale "
        "PENDING receipt is settled from its recorded execution as it is read, so asking for "
        "PENDING lists what is still genuinely unknown. Never rows."
    )
    async def governed_executions(
        self,
        info: Info,
        status: str | None = None,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
    ) -> GovernedExecutionReceiptConnection | None:
        scope = info.context
        if first < 1 or first > scope.limits.max_page_size:
            raise ReadRefused("INVALID_ARGUMENT", "PAGE_SIZE_OUT_OF_RANGE")
        async with scope.lock:
            try:
                page = await list_receipts(
                    scope.session,
                    scope.context,
                    scope.settings,
                    organization_id=scope.organization_id,
                    status=status,
                    first=first,
                    after=after,
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionReceiptConnection(
            nodes=[GovernedExecutionReceipt.of(record) for record in page.items],
            page_info=PageInfo(has_next_page=page.has_next_page, end_cursor=page.end_cursor),
            total_count=page.total,
        )

    @field_resolver(
        "One governed execution receipt (R11-GQL02): the caller's own, or any in the "
        "organization for PlatformAdmin and Auditor. Never rows."
    )
    async def governed_execution(
        self, info: Info, id: strawberry.ID
    ) -> GovernedExecutionReceipt | None:
        scope = info.context
        async with scope.lock:
            try:
                record = await load_receipt(
                    scope.session,
                    scope.context,
                    scope.settings,
                    organization_id=scope.organization_id,
                    record_id=_uuid(id),
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionReceipt.of(record)

    @field_resolver(
        "A project's context products, as `GET /v1/projects/{id}/context-products`: the "
        "lifecycle view, or with `askable` only the published products a role of the caller's "
        "may ask through; a contracted agent sees only what its envelope names."
    )
    async def context_products(
        self,
        info: Info,
        project_id: strawberry.ID,
        askable: bool = False,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
    ) -> ContextProductConnection | None:
        page = await list_context_products(
            info.context, _uuid(project_id), askable=askable, first=first, after=after
        )
        return ContextProductConnection.of(page)

    @field_resolver(
        "One context product version, as `GET /v1/context-product-versions/{id}` reads it -- "
        "envelope, role, retirement (`GONE`), purpose and quality -- and, for a consumer, "
        "recorded as a consumption on channel GRAPHQL."
    )
    async def context_product_version(
        self, info: Info, id: strawberry.ID
    ) -> ContextProductVersion | None:
        return ContextProductVersion.of(await get_context_product_version(info.context, _uuid(id)))

    @field_resolver(
        "Transitive impact from one lineage node, as "
        "`GET /v1/datasources/{id}/unified-lineage/impact/{node_id}`: the same traversal, "
        "bounds and quality states. Also asks the datasource's workspace gate, as its "
        "`tables` do."
    )
    async def lineage_impact(
        self,
        info: Info,
        datasource_id: strawberry.ID,
        node_id: str,
        depth: int = 5,
        node_limit: int = 200,
    ) -> LineageImpact | None:
        read = await get_lineage_impact(
            info.context, _uuid(datasource_id), node_id, depth=depth, node_limit=node_limit
        )
        return LineageImpact.of(read)

    @field_resolver(
        "A datasource's merged lineage graph, as "
        "`GET /v1/datasources/{id}/unified-lineage/graph`: the same merge, review filter and "
        "bounds. Also asks the datasource's workspace gate, as its `tables` do."
    )
    async def lineage_graph(
        self,
        info: Info,
        datasource_id: strawberry.ID,
        node_limit: int = 300,
        edge_limit: int = 1_500,
        suggestion_status: LineageSuggestionStatus = LineageSuggestionStatus.APPROVED,
        include_pending_edges: bool = False,
    ) -> LineageGraph | None:
        read = await get_lineage_graph(
            info.context,
            _uuid(datasource_id),
            node_limit=node_limit,
            edge_limit=edge_limit,
            suggestion_status=suggestion_status.value,
            include_pending_edges=include_pending_edges,
        )
        return LineageGraph.of(read)

    @field_resolver(
        "A context product version's coverage -- the routines and views it stands on, the "
        "meaning it pins, what moved since it was published, and each source's freshness -- as "
        "`GET /v1/context-product-versions/{id}/compile` resolves and decides it. Recorded as "
        "a read: an audit event, and a consumption for a PUBLISHED version."
    )
    async def context_product_coverage(
        self, info: Info, version_id: strawberry.ID
    ) -> ContextProductCoverage | None:
        return ContextProductCoverage.of(
            await get_context_product_coverage(info.context, _uuid(version_id))
        )

    @field_resolver(
        "How completely a routine's body was understood, as "
        "`GET /v1/datasources/{id}/procedures/{routine_id}/parse-coverage` decides and reads "
        "it, workspace gate included. NOT_FOUND with reason COVERAGE_NOT_MEASURED when no "
        "parse has measured it."
    )
    async def routine_parse_coverage(
        self, info: Info, datasource_id: strawberry.ID, routine_id: strawberry.ID
    ) -> RoutineParseCoverage | None:
        read = await get_routine_parse_coverage(
            info.context, _uuid(datasource_id), _uuid(routine_id)
        )
        return RoutineParseCoverage.of(read)

    @field_resolver(
        "How completely a trigger's body was understood, as "
        "`GET /v1/datasources/{id}/triggers/{trigger_id}/parse-coverage` decides and reads "
        "it, workspace gate included. NOT_FOUND with reason COVERAGE_NOT_MEASURED when no "
        "parse has measured it."
    )
    async def trigger_parse_coverage(
        self, info: Info, datasource_id: strawberry.ID, trigger_id: strawberry.ID
    ) -> TriggerParseCoverage | None:
        read = await get_trigger_parse_coverage(
            info.context, _uuid(datasource_id), _uuid(trigger_id)
        )
        return TriggerParseCoverage.of(read)

    @field_resolver(
        "A context product version's stored OKF knowledge bundle, as "
        "`GET /v1/context-product-versions/{id}/okf-bundle` reads it: the same store, and so "
        "the same envelope, consumer-role, purpose, quality and per-datasource decisions, and "
        "the same lineage keyed on what this caller's authorization admits. `publicationId` "
        "reads that retained publication of the caller's own lineage instead of the current "
        "one. Recorded as a read: an audit event, and a consumption for a PUBLISHED version."
    )
    async def context_product_okf_bundle(
        self, info: Info, version_id: strawberry.ID, publication_id: strawberry.ID | None = None
    ) -> OkfBundle | None:
        return OkfBundle.of(
            await get_okf_bundle(
                info.context, PRODUCT, _uuid(version_id), _optional_uuid(publication_id)
            )
        )

    @field_resolver(
        "One datasource's stored OKF knowledge bundle, as `GET /v1/datasources/{id}/okf-bundle` "
        "reads it: the datasource's `READ_METADATA` decision, and each schema's where a "
        "workspace decides, is taken on every read, and a caller it refuses is answered "
        "FORBIDDEN with the gate's own reason -- never an empty bundle. Only objects that "
        "decision admitted are named or counted. Recorded as a read."
    )
    async def datasource_okf_bundle(
        self, info: Info, datasource_id: strawberry.ID, publication_id: strawberry.ID | None = None
    ) -> OkfBundle | None:
        return OkfBundle.of(
            await get_okf_bundle(
                info.context, SOURCE, _uuid(datasource_id), _optional_uuid(publication_id)
            )
        )

    @field_resolver(
        "The stored OKF knowledge about one catalog object, as "
        "`GET /v1/metadata/tables/{id}/okf-knowledge` reads it (R11-OKF02): its document from "
        "each context product bundle the caller may read, or -- only when none holds it -- "
        "from its own datasource's bundle under that datasource's `READ_METADATA` decision. "
        "Recorded as a read."
    )
    async def object_okf_knowledge(
        self, info: Info, table_id: strawberry.ID
    ) -> OkfObjectKnowledge | None:
        return OkfObjectKnowledge.of(await read_object_okf(info.context, _uuid(table_id)))

    @field_resolver("One table by id, decided as its columns route decides it.")
    async def table(self, info: Info, id: strawberry.ID) -> Table | None:
        return Table.of_row(await get_table(info.context, _uuid(id)))

    @field_resolver(
        "Tables the caller may read. With `datasourceId`, as "
        "`GET /v1/datasources/{id}/tables`; without it, across the caller's organization, "
        "with unreadable datasources removed before counting and paging."
    )
    async def tables(
        self,
        info: Info,
        datasource_id: strawberry.ID | None = None,
        first: int = _DEFAULT_PAGE,
        after: str | None = None,
        q: str | None = None,
        object_type: str | None = None,
        status: str = "ACTIVE",
    ) -> TableConnection | None:
        if datasource_id is not None:
            page = await list_datasource_tables(
                info.context,
                _uuid(datasource_id),
                first=first,
                after=after,
                q=q,
                object_type=object_type,
                status=status,
            )
        else:
            page = await list_organization_tables(
                info.context, first=first, after=after, q=q, object_type=object_type, status=status
            )
        return TableConnection.of(page)


# --- governed execution (R11-GQL02) -------------------------------------------


@strawberry.input(description="One governed execution request (R11-GQL02).")
class ExecuteGovernedToolInput:
    tool_version_id: strawberry.ID = strawberry.field(
        description="A PUBLISHED governed tool version. Nothing else can be executed here."
    )
    idempotency_key: str = strawberry.field(
        description=(
            "8-128 characters of `A-Z a-z 0-9 . _ : -`, chosen by the caller. Sending the same "
            "key again with the same inputs returns the first request's receipt and executes "
            "nothing; the same key with different inputs is refused."
        )
    )
    max_rows: int = strawberry.field(
        description="The row limit, required and explicit; at most the endpoint's execution cap."
    )
    parameters: JSON | None = strawberry.field(
        default=None, description="The tool version's typed parameters, as a JSON object."
    )
    context_product_key: str | None = strawberry.field(
        default=None,
        description=(
            "Execute through this published context product: the tool must be eligible in it "
            "and read only its tables."
        ),
    )


@strawberry.type(
    description=(
        "The durable record of one requested governed execution. Never rows: a receipt is "
        "what can be read again."
    )
)
class GovernedExecutionReceipt:
    id: strawberry.ID
    status: str = strawberry.field(
        description=(
            "PENDING (running, or ended without the platform learning its outcome -- never "
            "retried as a new execution, and settled from the recorded execution once it "
            "cannot still be running), COMPLETED, REJECTED or FAILED (`NOT_STARTED` when "
            "nothing reached the source)."
        )
    )
    tool_version_id: strawberry.ID
    tool_execution_id: strawberry.ID | None
    query_execution_id: strawberry.ID | None
    context_product_version_id: strawberry.ID | None
    row_count: int | None
    outcome_code: str | None = strawberry.field(
        description="A stable refusal or failure code; never a message."
    )
    created_at: datetime
    completed_at: datetime | None

    @classmethod
    def of(cls, record: GovernedExecutionRequest) -> GovernedExecutionReceipt:
        def optional(value: UUID | None) -> strawberry.ID | None:
            return _id(value) if value is not None else None

        return cls(
            id=_id(record.id),
            status=record.status,
            tool_version_id=_id(record.tool_version_id),
            tool_execution_id=optional(record.tool_execution_id),
            query_execution_id=optional(record.query_execution_id),
            context_product_version_id=optional(record.context_product_version_id),
            row_count=record.row_count,
            outcome_code=record.outcome_code,
            created_at=record.created_at,
            completed_at=record.completed_at,
        )


@strawberry.type(description="A page of execution receipts, newest first.")
class GovernedExecutionReceiptConnection:
    nodes: list[GovernedExecutionReceipt]
    page_info: PageInfo
    total_count: int | None


@strawberry.type(
    description=(
        "The rows one execution returned, after the gateway masked them. Present only in the "
        "response of the request that executed; never stored, never replayed."
    )
)
class GovernedExecutionResult:
    columns: list[str]
    rows: JSON = strawberry.field(description="One array per row, in `columns` order.")
    masked_columns: list[str]
    applied_row_limit: int | None


@strawberry.type(description="What an execution mutation answered.")
class GovernedExecutionOutcome:
    receipt: GovernedExecutionReceipt
    replayed: bool = strawberry.field(
        description="True when this key had already been used: nothing executed for this request."
    )
    result: GovernedExecutionResult | None
    quality_gate_action: str | None = strawberry.field(
        description="WARN when an upstream dependency has an open, non-critical quality incident."
    )

    @classmethod
    def of(cls, outcome: ExecutionOutcome) -> GovernedExecutionOutcome:
        response = outcome.response
        result: GovernedExecutionResult | None = None
        gate: str | None = None
        if response is not None:
            execution = response.execution
            columns = list(execution.rows[0].keys()) if execution.rows else []
            result = GovernedExecutionResult(
                columns=columns,
                rows=cast(
                    "JSON", [[row.get(column) for column in columns] for row in execution.rows]
                ),
                masked_columns=list(execution.masked_columns),
                applied_row_limit=execution.applied_row_limit,
            )
            gate = str(response.quality_gate["action"]) if response.quality_gate else None
        return cls(
            receipt=GovernedExecutionReceipt.of(outcome.record),
            replayed=outcome.replayed,
            result=result,
            quality_gate_action=gate,
        )


@strawberry.type(
    description=(
        "Governed execution (R11-GQL02): the only operations that run anything against a "
        "source. One execution field per operation."
    )
)
class Mutation:
    @field_resolver(
        "Execute one approved tool version once for this caller and idempotency key, through "
        "the same governed path as `POST /v1/tool-versions/{version_id}/execute`."
    )
    async def execute_governed_tool(
        self, info: Info, request: ExecuteGovernedToolInput
    ) -> GovernedExecutionOutcome | None:
        scope = info.context
        if not 1 <= request.max_rows <= scope.limits.max_execution_rows:
            raise ReadRefused("INVALID_ARGUMENT", "MAX_ROWS_OUT_OF_RANGE")
        parameters: Any = request.parameters if request.parameters is not None else {}
        if not isinstance(parameters, dict):
            raise ReadRefused("INVALID_ARGUMENT", "PARAMETERS_NOT_AN_OBJECT")
        async with scope.lock:
            try:
                outcome = await execute_governed_tool(
                    scope.session,
                    scope.settings,
                    context=scope.context,
                    organization_id=scope.organization_id,
                    tool_version_id=_uuid(request.tool_version_id),
                    parameters=parameters,
                    max_rows=request.max_rows,
                    context_product_key=request.context_product_key,
                    idempotency_key=request.idempotency_key,
                    correlation_id=get_correlation_id(),
                )
            except ExecutionRefused as refused:
                raise ReadRefused(refused.code, refused.reason) from refused
        return GovernedExecutionOutcome.of(outcome)


def error_code(error: GraphQLError) -> tuple[str, str | None]:
    """The stable (code, reason) for one execution error. Anything that is not a
    deliberate refusal is INTERNAL_ERROR, with no message of its own."""
    original = error.original_error
    if isinstance(original, ReadRefused):
        return original.code, original.reason
    if original is None:
        return "VALIDATION_FAILED", None
    return "INTERNAL_ERROR", None


class _MetadataSchema(strawberry.Schema):
    """Strawberry's schema, with value-free error logging.

    Strawberry's default logs every error with its traceback, and an exception
    raised inside SQLAlchemy carries the statement text and its bound parameters
    -- exactly what INV-6 keeps out of logs. Only the stable code, the exception
    type and the depth of the path are recorded here.
    """

    def process_errors(
        self,
        errors: list[GraphQLError],
        execution_context: ExecutionContext | None = None,
    ) -> None:
        for error in errors:
            code, reason = error_code(error)
            original = error.original_error
            fields = {
                "code": code,
                "reason": reason,
                "path_depth": len(error.path or ()),
                "error_type": type(original).__name__ if original is not None else None,
            }
            if code == "INTERNAL_ERROR":
                _log.error("graphql.resolver_failed", **fields)
            else:
                _log.info("graphql.field_refused", **fields)


class _ScopedIntrospection(SchemaExtension):
    """Introspection only where this request's admission allowed it.

    The endpoint decides per caller (`graphql_limits.introspection_decision`) and refuses a
    disallowed document before execution; this is the backstop for any other way into
    `metadata_schema.execute`. It adds graphql-core's no-introspection rule -- what
    strawberry's `DisableIntrospection` adds -- unless the context is a `ReadScope` whose
    limits allow introspection, so a context of any other kind never introspects.
    """

    def on_operation(self) -> Iterator[None]:
        scope = self.execution_context.context
        allowed = isinstance(scope, ReadScope) and scope.limits.allow_introspection
        if not allowed:
            self.execution_context.validation_rules = (
                *self.execution_context.validation_rules,
                NoSchemaIntrospectionCustomRule,
            )
        yield


def _backstops() -> list[Callable[[], SchemaExtension]]:
    """Strawberry's own limiters, set no tighter than the endpoint's admission
    check. The endpoint refuses first; these guard `metadata_schema.execute`
    against a caller that reaches it by any other route.

    Set at `LIMIT_CEILINGS`, the largest value a deployment may configure each limit
    to, so a raised `graphql_*` setting is never undone by a backstop that still holds
    the default. Introspection is decided per request (`_ScopedIntrospection`).

    Factories, not instances: strawberry builds a fresh extension per request
    from each, so no extension state is ever shared between two callers.
    """
    ceilings = LIMIT_CEILINGS
    return [
        lambda: MaxTokensLimiter(max_token_count=ceilings.max_tokens),
        lambda: MaxAliasesLimiter(max_alias_count=ceilings.max_aliases),
        lambda: QueryDepthLimiter(max_depth=ceilings.max_depth),
        _ScopedIntrospection,
    ]


metadata_schema = _MetadataSchema(
    query=Query,
    mutation=Mutation,
    extensions=_backstops(),
    config=StrawberryConfig(disable_field_suggestions=True),
)
