/* ---------------------------------------------------------------------------
   The browser's authorization-code + PKCE flow (review 2026-09-05, F06 · T07).

   THE DEFECT this module removes: `authSession.ts` held a token and put it on
   the wire, and `App.tsx` rendered a screen explaining that nothing could ever
   put a token there. The seam (`adoptAccessToken`) existed; the half that
   obtains a token did not. Against an OIDC backend the app therefore could
   not be signed into at all, which is what F06's acceptance criterion --
   "fresh-browser sign-in works through the actual topology" -- names.

   THE INVARIANT: the only way an access token enters this application is a
   completed authorization-code exchange whose PKCE verifier and `state` were
   generated by THIS document and never left it. A response carrying a `code`
   we have no matching transaction for is discarded, not exchanged.

   WHAT IS IN sessionStorage AND WHY IT IS NOT THE TOKEN. The verifier, the
   `state` and the `nonce` have to survive a full-page redirect to the IdP and
   back, so they cannot live in a module variable. They are not credentials on
   their own: the verifier is useless without the single-use authorization
   code, is discarded the moment the exchange completes or fails, and is
   scoped to the tab. The access token and the refresh token stay in memory
   (`authSession.ts`, and `refreshToken` below) exactly as before -- a token in
   web storage is readable by any script injected into this origin and would
   outlive the tab, which is the exposure the current design deliberately
   avoids. Do not "simplify" this by parking the token next to the verifier.

   WHY DISCOVERY RATHER THAN CONFIGURED ENDPOINTS: an IdP owns its endpoint
   URLs and is entitled to move them. Reading `.well-known/openid-configuration`
   means one configuration item (the issuer) instead of four that can drift out
   of step with each other.

   WHY `fetch` IS CALLED HERE. `lib/api/transport.ts` is the single transport
   for the *product API*, and it attaches this application's identity headers.
   The token endpoint is a different server with a different authentication
   model, and sending Atlas identity headers to an IdP would be both wrong and
   a small information leak. This is the IdP client, not a second API client.
--------------------------------------------------------------------------- */

import { APP_CONFIG, type AppConfig, type OidcClientConfig } from "./appConfig";
import {
  accessTokenExpiresAt,
  adoptAccessToken,
  clearAccessToken,
  noteSignInFailure,
} from "./authSession";

/** Where the in-flight authorization request is remembered across the redirect. */
export const PKCE_TRANSACTION_KEY = "atlas.oidc.txn";

export interface PkcePair {
  readonly verifier: string;
  readonly challenge: string;
}

interface PendingTransaction {
  readonly state: string;
  readonly nonce: string;
  readonly verifier: string;
  readonly redirectUri: string;
  readonly issuer: string;
  /** Where the user was before being redirected, so sign-in returns them there. */
  readonly returnTo: string;
  readonly startedAt: number;
}

interface Discovery {
  readonly authorization_endpoint: string;
  readonly token_endpoint: string;
  readonly revocation_endpoint?: string;
  readonly end_session_endpoint?: string;
}

interface TokenResponse {
  readonly access_token: string;
  readonly expires_in?: number;
  readonly refresh_token?: string;
  readonly token_type?: string;
}

/** An authorization request older than this is stale; a `code` for it is refused. */
const TRANSACTION_TTL_MS = 10 * 60 * 1000;

/* Renew this many seconds before the access token expires. A token shorter
 * than twice this is renewed at its half-life instead, so a deliberately
 * short-lived token (which is how expiry and renewal get tested at all) is
 * not renewed either immediately or too late. */
const RENEW_SKEW_SECONDS = 60;
const MIN_RENEW_DELAY_MS = 2_000;

/** In memory, like the access token, and for the same reason. */
let refreshToken: string | null = null;
let renewTimer: ReturnType<typeof setTimeout> | null = null;
let discoveryCache: { issuer: string; document: Discovery } | null = null;

function base64Url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function randomUrlSafe(byteLength: number): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  return base64Url(bytes);
}

/**
 * A PKCE verifier and its S256 challenge (RFC 7636).
 *
 * `crypto.subtle` exists only in a secure context. `http://localhost` is one;
 * plain `http://` on any other host is not, and there the digest is simply
 * absent. Falling back to `code_challenge_method=plain` there would send the
 * verifier itself in the authorization request -- PKCE with the protection
 * removed and the appearance of it kept. This throws instead, and the sign-in
 * screen reports why.
 */
export async function createPkcePair(): Promise<PkcePair> {
  if (typeof crypto === "undefined" || !crypto.subtle) {
    throw new Error(
      "PKCE requires a secure context (HTTPS, or http://localhost). This page is served " +
        "over plain HTTP from another host, so the browser withholds crypto.subtle and no " +
        "S256 challenge can be computed.",
    );
  }
  const verifier = randomUrlSafe(48);
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
  return { verifier, challenge: base64Url(new Uint8Array(digest)) };
}

export function oidcConfig(config: AppConfig = APP_CONFIG): OidcClientConfig | null {
  return config.authMode === "oidc" ? config.oidc : null;
}

/** True when this build is configured to run a flow of its own. */
export function canStartSignIn(config: AppConfig = APP_CONFIG): boolean {
  return oidcConfig(config) !== null;
}

function redirectUriFor(oidc: OidcClientConfig): string {
  return new URL(oidc.redirectPath, window.location.origin).toString();
}

async function discover(issuer: string): Promise<Discovery> {
  if (discoveryCache?.issuer === issuer) return discoveryCache.document;
  const url = `${issuer.replace(/\/+$/, "")}/.well-known/openid-configuration`;
  const response = await fetch(url, { headers: { Accept: "application/json" } });
  if (!response.ok) {
    throw new Error(`the identity provider's discovery document is unavailable (${response.status})`);
  }
  const document = (await response.json()) as Discovery;
  if (!document.authorization_endpoint || !document.token_endpoint) {
    throw new Error("the identity provider's discovery document names no authorization or token endpoint");
  }
  discoveryCache = { issuer, document };
  return document;
}

function storeTransaction(transaction: PendingTransaction): void {
  sessionStorage.setItem(PKCE_TRANSACTION_KEY, JSON.stringify(transaction));
}

function takeTransaction(): PendingTransaction | null {
  let raw: string | null = null;
  try {
    raw = sessionStorage.getItem(PKCE_TRANSACTION_KEY);
    // Single use, always: read and remove together, so a replayed callback URL
    // finds nothing to exchange even if the code itself were still live.
    sessionStorage.removeItem(PKCE_TRANSACTION_KEY);
  } catch {
    return null;
  }
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw) as PendingTransaction;
    if (!parsed.state || !parsed.verifier || !parsed.redirectUri) return null;
    if (Date.now() - parsed.startedAt > TRANSACTION_TTL_MS) return null;
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Build the authorization request and remember the transaction that has to
 * survive the redirect.
 *
 * Separate from `beginSignIn` because everything security-relevant about the
 * redirect -- that `state` and the verifier are freshly generated here, that
 * the challenge is S256 and not the verifier itself, that the stored
 * transaction matches what is sent -- is decided in this function, and a
 * function that ends by replacing the document cannot be asserted on.
 */
export async function prepareAuthorizationRequest(
  config: AppConfig = APP_CONFIG,
): Promise<string> {
  const oidc = oidcConfig(config);
  if (!oidc) throw new Error("this build has no identity provider configured");
  const discovery = await discover(oidc.issuer);
  const { verifier, challenge } = await createPkcePair();
  const state = randomUrlSafe(24);
  const nonce = randomUrlSafe(24);
  const redirectUri = redirectUriFor(oidc);
  storeTransaction({
    state,
    nonce,
    verifier,
    redirectUri,
    issuer: oidc.issuer,
    returnTo: `${window.location.search}${window.location.hash}`,
    startedAt: Date.now(),
  });
  const authorize = new URL(discovery.authorization_endpoint);
  authorize.searchParams.set("response_type", "code");
  authorize.searchParams.set("client_id", oidc.clientId);
  authorize.searchParams.set("redirect_uri", redirectUri);
  authorize.searchParams.set("scope", oidc.scope);
  authorize.searchParams.set("state", state);
  authorize.searchParams.set("nonce", nonce);
  authorize.searchParams.set("code_challenge", challenge);
  authorize.searchParams.set("code_challenge_method", "S256");
  return authorize.toString();
}

/**
 * Start the redirect to the identity provider.
 *
 * Returns only if the redirect could not be started; on success the document
 * is being replaced and nothing after the assignment runs.
 */
export async function beginSignIn(config: AppConfig = APP_CONFIG): Promise<void> {
  window.location.assign(await prepareAuthorizationRequest(config));
}

export type CallbackOutcome =
  | { readonly kind: "none" }
  | { readonly kind: "signed-in" }
  | { readonly kind: "failed"; readonly message: string };

/**
 * The authorization response carried in a URL, or null when there is none.
 *
 * Split out from the exchange so the parsing rules -- which are the security
 * rules -- can be tested without a network or a redirect.
 */
export function readAuthorizationResponse(
  search: string,
): { code: string; state: string } | { error: string } | null {
  const params = new URLSearchParams(search.replace(/^\?/, ""));
  const error = params.get("error");
  if (error) {
    const description = params.get("error_description");
    return { error: description ? `${error}: ${description}` : error };
  }
  const code = params.get("code");
  const state = params.get("state");
  if (!code || !state) return null;
  return { code, state };
}

/** Remove the authorization response from the address bar without a navigation. */
function scrubCallbackFromUrl(returnTo: string): void {
  const target = `${window.location.pathname}${returnTo || window.location.hash}`;
  history.replaceState(null, "", target);
}

async function exchange(
  tokenEndpoint: string,
  body: Record<string, string>,
): Promise<TokenResponse> {
  const response = await fetch(tokenEndpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Accept: "application/json",
    },
    body: new URLSearchParams(body).toString(),
  });
  const payload = (await response.json().catch(() => null)) as
    | (TokenResponse & { error?: string; error_description?: string })
    | null;
  if (!response.ok || !payload?.access_token) {
    const detail = payload?.error_description ?? payload?.error ?? `HTTP ${response.status}`;
    throw new Error(`the identity provider refused the token request (${detail})`);
  }
  return payload;
}

function cancelRenewal(): void {
  if (renewTimer !== null) {
    clearTimeout(renewTimer);
    renewTimer = null;
  }
}

/**
 * Adopt a token response and arm the renewal that keeps the session alive.
 *
 * A session that simply dies at `expires_in` would make every deployment
 * choose between an hour-long token and an hour-long-at-most session. Renewal
 * is scheduled from the issuer's own `expires_in`, never from a guess.
 */
function adoptTokenResponse(response: TokenResponse, config: AppConfig): void {
  const lifetime = typeof response.expires_in === "number" ? response.expires_in : undefined;
  refreshToken = response.refresh_token ?? refreshToken;
  adoptAccessToken(response.access_token, lifetime);
  cancelRenewal();
  if (lifetime === undefined || refreshToken === null) return;
  const seconds =
    lifetime > RENEW_SKEW_SECONDS * 2 ? lifetime - RENEW_SKEW_SECONDS : lifetime / 2;
  renewTimer = setTimeout(
    () => {
      void renewAccessToken(config);
    },
    Math.max(seconds * 1000, MIN_RENEW_DELAY_MS),
  );
}

/**
 * End the renewal side of the session without touching the access token.
 *
 * The token that is still in hand stays valid until its own `exp` -- a grant
 * that can no longer be refreshed does not retroactively invalidate what it
 * already issued. `authSession` then reports the lapse when that moment
 * arrives, which is what the shell shows.
 */
function stopRenewing(reason: string): void {
  cancelRenewal();
  refreshToken = null;
  noteSignInFailure(reason);
}

/**
 * Exchange the refresh token for a new access token.
 *
 * A RENEWAL MUST EXTEND THE SESSION, BY MORE THAN THE INTERVAL IT COSTS.
 * Verified against a real issuer, the naive version -- adopt whatever comes
 * back and schedule the next renewal from its `expires_in` -- locked into a
 * request every two seconds forever: the issuer kept re-issuing tokens with
 * the SAME absolute `exp`, each one a shorter `expires_in` than the last, and
 * the client kept asking. "Not earlier than before" is not a strong enough
 * test either, because sub-second rounding lets a re-issue of the same
 * deadline look like a few milliseconds of progress. The deadline has to move
 * by more than the minimum gap between two renewals, or renewal is doing no
 * work and the session is allowed to lapse honestly.
 *
 * A transport failure is the same end of session by a different route -- the
 * IdP is unreachable, or it has revoked the grant.
 */
export async function renewAccessToken(config: AppConfig = APP_CONFIG): Promise<boolean> {
  const oidc = oidcConfig(config);
  if (!oidc || refreshToken === null) return false;
  const previousExpiry = accessTokenExpiresAt();
  try {
    const discovery = await discover(oidc.issuer);
    const response = await exchange(discovery.token_endpoint, {
      grant_type: "refresh_token",
      client_id: oidc.clientId,
      refresh_token: refreshToken,
      scope: oidc.scope,
    });
    const lifetime = typeof response.expires_in === "number" ? response.expires_in : undefined;
    const renewedExpiry = lifetime === undefined ? null : Date.now() + lifetime * 1000;
    if (renewedExpiry !== null && renewedExpiry <= Date.now()) {
      stopRenewing("the identity provider re-issued a token that had already expired");
      return false;
    }
    if (
      renewedExpiry !== null &&
      previousExpiry !== null &&
      renewedExpiry <= previousExpiry + MIN_RENEW_DELAY_MS
    ) {
      stopRenewing(
        "the identity provider re-issued a token expiring no later than the current one, " +
          "so this session cannot be extended further",
      );
      return false;
    }
    adoptTokenResponse(response, config);
    return true;
  } catch (cause) {
    stopRenewing(cause instanceof Error ? cause.message : String(cause));
    return false;
  }
}

/**
 * Complete a sign-in if this page load is an authorization response.
 *
 * Called once, from `main.tsx`, BEFORE React renders. Doing it in an effect
 * would run it twice under `StrictMode` and burn the single-use code on the
 * second call, and would flash the sign-in screen in between.
 */
export async function completePendingSignIn(
  config: AppConfig = APP_CONFIG,
): Promise<CallbackOutcome> {
  const oidc = oidcConfig(config);
  if (!oidc || typeof window === "undefined") return { kind: "none" };
  const response = readAuthorizationResponse(window.location.search);
  if (response === null) return { kind: "none" };
  const transaction = takeTransaction();
  if ("error" in response) {
    scrubCallbackFromUrl(transaction?.returnTo ?? "");
    noteSignInFailure(response.error);
    return { kind: "failed", message: response.error };
  }
  if (transaction === null) {
    // A `code` with no transaction of ours is either a stale bookmark or an
    // authorization response this document did not ask for. Either way it is
    // not exchanged: that check is what `state` is for.
    scrubCallbackFromUrl("");
    return { kind: "none" };
  }
  if (transaction.state !== response.state) {
    scrubCallbackFromUrl(transaction.returnTo);
    const message = "the identity provider's response did not match this browser's sign-in request";
    noteSignInFailure(message);
    return { kind: "failed", message };
  }
  try {
    const discovery = await discover(transaction.issuer);
    const tokens = await exchange(discovery.token_endpoint, {
      grant_type: "authorization_code",
      client_id: oidc.clientId,
      code: response.code,
      redirect_uri: transaction.redirectUri,
      code_verifier: transaction.verifier,
    });
    adoptTokenResponse(tokens, config);
    scrubCallbackFromUrl(transaction.returnTo);
    return { kind: "signed-in" };
  } catch (cause) {
    scrubCallbackFromUrl(transaction.returnTo);
    const message = cause instanceof Error ? cause.message : String(cause);
    noteSignInFailure(message);
    return { kind: "failed", message };
  }
}

/**
 * End the session in this browser, and tell the issuer if it will listen.
 *
 * Dropping the tokens here is the part that must not fail: whatever the IdP
 * does with the revocation request, this browser is signed out afterwards.
 */
export function signOut(config: AppConfig = APP_CONFIG): void {
  const oidc = oidcConfig(config);
  const revoking = refreshToken;
  cancelRenewal();
  refreshToken = null;
  clearAccessToken();
  if (!oidc || revoking === null) return;
  void discover(oidc.issuer)
    .then((discovery) => {
      if (!discovery.revocation_endpoint) return;
      return fetch(discovery.revocation_endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          token: revoking,
          token_type_hint: "refresh_token",
          client_id: oidc.clientId,
        }).toString(),
      }).then(() => undefined);
    })
    .catch(() => undefined);
}

/** Reset for tests. Not part of the runtime contract. */
export function resetOidcClientForTests(): void {
  cancelRenewal();
  refreshToken = null;
  discoveryCache = null;
}

/** Whether a renewal is currently armed. Exposed for tests and diagnostics. */
export function hasPendingRenewal(): boolean {
  return renewTimer !== null;
}
