"""dbt_resource_test_and_extra_metadata

Revision ID: 04003a3d6945
Revises: 8a7f3c1d4b22
Create Date: 2026-08-28 11:18:09.462007
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "04003a3d6945"
down_revision: str | Sequence[str] | None = "8a7f3c1d4b22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dbt_resource", sa.Column("test_status", sa.String(length=30), nullable=True))
    op.add_column("dbt_resource", sa.Column("test_failures", sa.Integer(), nullable=True))
    op.add_column("dbt_resource", sa.Column("test_execution_time", sa.Float(), nullable=True))
    op.add_column(
        "dbt_resource",
        sa.Column(
            "extra_metadata", sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbt_resource", "extra_metadata")
    op.drop_column("dbt_resource", "test_execution_time")
    op.drop_column("dbt_resource", "test_failures")
    op.drop_column("dbt_resource", "test_status")
    # ### end Alembic commands ###
