"""AU-8: reconcile ORM/migration drift found by tests/test_migration_orm_drift.py

Closes drift the branch's fast pace let accumulate silently (tracker AU-8,
Docs/60-delivery/04-end-to-end-audit-2026-08-30.md Section 5): eight ORM
tables with no migration, five columns added to `composite_key_candidate`
without one, a `data_quality_incident.latest_observation_id` FK/nullability
mismatch, three columns migrated as JSONB against the codebase's JSON
convention (43 other migrations use `sa.JSON`; this was the one outlier),
and one differently-named unique constraint. See that test file's docstring
and Docs/60-delivery/03-tracker.md row AU-8 for how each item was verified
against Base.metadata rather than assumed.

Revision ID: 09be3ab5b008
Revises: bb909675ad3c
Create Date: 2026-08-31 11:04:53.657810
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "09be3ab5b008"
down_revision: str | Sequence[str] | None = "bb909675ad3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumption_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("consumer_id", sa.String(length=255), nullable=False),
        sa.Column("consumer_type", sa.String(length=30), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("policy_decision", sa.String(length=30), nullable=False),
        sa.Column("business_purpose", sa.String(length=200), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "channel IN ('MCP', 'REST', 'GRAPHQL', 'EVENT', 'INTERNAL')",
            name="ck_consumption_record_channel",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_consumption_record_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumption_record")),
    )
    op.create_index(
        "ix_consumption_record_consumer",
        "consumption_record",
        ["organization_id", "consumer_id", "consumed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_record_correlation_id"),
        "consumption_record",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_record_organization_id"),
        "consumption_record",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_consumption_record_resource",
        "consumption_record",
        ["organization_id", "resource_type", "resource_id", "consumed_at"],
        unique=False,
    )
    op.create_table(
        "negative_assertion",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("assertion_type", sa.String(length=50), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("predicate", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("rejected_by", sa.String(length=255), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suppression_active", sa.Boolean(), nullable=False),
        sa.Column("material_change_hash", sa.String(length=64), nullable=True),
        sa.Column("suppression_lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suppression_lifted_by", sa.String(length=255), nullable=True),
        sa.Column("lift_reason", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_negative_assertion_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negative_assertion")),
    )
    op.create_index(
        "ix_negative_assertion_org_subject",
        "negative_assertion",
        ["organization_id", "subject_id"],
        unique=False,
    )
    op.create_index(
        "ix_negative_assertion_org_type",
        "negative_assertion",
        ["organization_id", "assertion_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_negative_assertion_organization_id"),
        "negative_assertion",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_negative_assertion_subject_id"), "negative_assertion", ["subject_id"], unique=False
    )
    op.create_index(
        "ix_negative_assertion_suppression",
        "negative_assertion",
        ["organization_id", "suppression_active"],
        unique=False,
    )
    op.create_table(
        "search_index",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("index_key", sa.String(length=100), nullable=False),
        sa.Column("index_type", sa.String(length=30), nullable=False),
        sa.Column("source_table", sa.String(length=100), nullable=False),
        sa.Column("text_columns", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_rebuilt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_search_index_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_index")),
        sa.UniqueConstraint(
            "organization_id", "index_key", name=op.f("uq_search_index_organization_id")
        ),
    )
    op.create_index(
        "ix_search_index_org_status", "search_index", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_search_index_organization_id"), "search_index", ["organization_id"], unique=False
    )
    op.create_table(
        "vector_embedding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=True),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_vector_embedding_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_vector_embedding_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vector_embedding")),
        sa.UniqueConstraint(
            "organization_id",
            "object_type",
            "object_id",
            name=op.f("uq_vector_embedding_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_vector_embedding_datasource_id"),
        "vector_embedding",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_embedding_object_id"), "vector_embedding", ["object_id"], unique=False
    )
    op.create_index(
        "ix_vector_embedding_org_type",
        "vector_embedding",
        ["organization_id", "object_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_embedding_organization_id"),
        "vector_embedding",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "freshness_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("watermark_value", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_freshness_observation_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_freshness_observation_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_freshness_observation_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freshness_observation")),
    )
    op.create_index(
        op.f("ix_freshness_observation_datasource_id"),
        "freshness_observation",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_freshness_observation_organization_id"),
        "freshness_observation",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_freshness_observation_table_id"),
        "freshness_observation",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        "ix_freshness_observation_table_time",
        "freshness_observation",
        ["table_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "freshness_watermark_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("watermark_column", sa.String(length=255), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("threshold_minutes", sa.Integer(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_freshness_watermark_config_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_freshness_watermark_config_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_freshness_watermark_config_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freshness_watermark_config")),
        sa.UniqueConstraint("table_id", name=op.f("uq_freshness_watermark_config_table_id")),
    )
    op.create_index(
        op.f("ix_freshness_watermark_config_datasource_id"),
        "freshness_watermark_config",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_freshness_watermark_config_organization_id"),
        "freshness_watermark_config",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_freshness_watermark_config_table_id"),
        "freshness_watermark_config",
        ["table_id"],
        unique=False,
    )
    op.create_table(
        "procedure_lineage_edge",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("source_table", sa.String(length=500), nullable=False),
        sa.Column("source_column", sa.String(length=255), nullable=False),
        sa.Column("target_table", sa.String(length=500), nullable=False),
        sa.Column("target_column", sa.String(length=255), nullable=False),
        sa.Column("source_table_id", sa.Uuid(), nullable=True),
        sa.Column("source_column_id", sa.Uuid(), nullable=True),
        sa.Column("target_table_id", sa.Uuid(), nullable=True),
        sa.Column("target_column_id", sa.Uuid(), nullable=True),
        sa.Column("transformation_type", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("dialect", sa.String(length=50), nullable=False),
        sa.Column("sql_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_procedure_lineage_edge_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_procedure_lineage_edge_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["metadata_column.id"],
            name=op.f("fk_procedure_lineage_edge_source_column_id_metadata_column"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_table_id"],
            ["metadata_table.id"],
            name=op.f("fk_procedure_lineage_edge_source_table_id_metadata_table"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["metadata_column.id"],
            name=op.f("fk_procedure_lineage_edge_target_column_id_metadata_column"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_table_id"],
            ["metadata_table.id"],
            name=op.f("fk_procedure_lineage_edge_target_table_id_metadata_table"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procedure_lineage_edge")),
    )
    op.create_index(
        "ix_procedure_lineage_edge_datasource",
        "procedure_lineage_edge",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_datasource_id"),
        "procedure_lineage_edge",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        "ix_procedure_lineage_edge_org_target",
        "procedure_lineage_edge",
        ["organization_id", "target_table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_organization_id"),
        "procedure_lineage_edge",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_source_column_id"),
        "procedure_lineage_edge",
        ["source_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_source_table_id"),
        "procedure_lineage_edge",
        ["source_table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_target_column_id"),
        "procedure_lineage_edge",
        ["target_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procedure_lineage_edge_target_table_id"),
        "procedure_lineage_edge",
        ["target_table_id"],
        unique=False,
    )
    op.create_table(
        "view_lineage_edge",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("source_table", sa.String(length=500), nullable=False),
        sa.Column("source_column", sa.String(length=255), nullable=False),
        sa.Column("target_table", sa.String(length=500), nullable=False),
        sa.Column("target_column", sa.String(length=255), nullable=False),
        sa.Column("source_table_id", sa.Uuid(), nullable=True),
        sa.Column("source_column_id", sa.Uuid(), nullable=True),
        sa.Column("target_table_id", sa.Uuid(), nullable=True),
        sa.Column("target_column_id", sa.Uuid(), nullable=True),
        sa.Column("transformation_type", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("dialect", sa.String(length=50), nullable=False),
        sa.Column("sql_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_view_lineage_edge_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_view_lineage_edge_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_column_id"],
            ["metadata_column.id"],
            name=op.f("fk_view_lineage_edge_source_column_id_metadata_column"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_table_id"],
            ["metadata_table.id"],
            name=op.f("fk_view_lineage_edge_source_table_id_metadata_table"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_column_id"],
            ["metadata_column.id"],
            name=op.f("fk_view_lineage_edge_target_column_id_metadata_column"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_table_id"],
            ["metadata_table.id"],
            name=op.f("fk_view_lineage_edge_target_table_id_metadata_table"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_view_lineage_edge")),
    )
    op.create_index(
        "ix_view_lineage_edge_datasource", "view_lineage_edge", ["datasource_id"], unique=False
    )
    op.create_index(
        op.f("ix_view_lineage_edge_datasource_id"),
        "view_lineage_edge",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        "ix_view_lineage_edge_org_target",
        "view_lineage_edge",
        ["organization_id", "target_table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_view_lineage_edge_organization_id"),
        "view_lineage_edge",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_view_lineage_edge_source_column_id"),
        "view_lineage_edge",
        ["source_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_view_lineage_edge_source_table_id"),
        "view_lineage_edge",
        ["source_table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_view_lineage_edge_target_column_id"),
        "view_lineage_edge",
        ["target_column_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_view_lineage_edge_target_table_id"),
        "view_lineage_edge",
        ["target_table_id"],
        unique=False,
    )
    op.alter_column(
        "ai_remediation",
        "resolution_evidence",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "ai_trust_snapshot",
        "factors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_trust_snapshot",
        "blockers",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("audit_archive_record_archive_id_key"), "audit_archive_record", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_audit_archive_record_archive_id"), "audit_archive_record", ["archive_id"]
    )
    op.add_column(
        "composite_key_candidate", sa.Column("table_profile_id", sa.Uuid(), nullable=True)
    )
    op.add_column("composite_key_candidate", sa.Column("column_names", sa.JSON(), nullable=False))
    op.add_column(
        "composite_key_candidate", sa.Column("column_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "composite_key_candidate",
        sa.Column("key_fingerprint", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "composite_key_candidate",
        sa.Column("estimated_distinctness_ratio", sa.Float(), nullable=False),
    )
    op.create_index(
        op.f("ix_composite_key_candidate_table_profile_id"),
        "composite_key_candidate",
        ["table_profile_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_composite_key_candidate_table_profile_id_table_profile"),
        "composite_key_candidate",
        "table_profile",
        ["table_profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "data_quality_incident", "latest_observation_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_data_quality_incident_latest_observation_id_data_qua_3a3b"),
        "data_quality_incident",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_data_quality_incident_latest_observation_id_data_quality_observation"),
        "data_quality_incident",
        "data_quality_observation",
        ["latest_observation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_data_quality_incident_latest_observation_id_data_quality_observation"),
        "data_quality_incident",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_data_quality_incident_latest_observation_id_data_qua_3a3b"),
        "data_quality_incident",
        "data_quality_observation",
        ["latest_observation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "data_quality_incident", "latest_observation_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        op.f("fk_composite_key_candidate_table_profile_id_table_profile"),
        "composite_key_candidate",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_composite_key_candidate_table_profile_id"), table_name="composite_key_candidate"
    )
    op.drop_column("composite_key_candidate", "estimated_distinctness_ratio")
    op.drop_column("composite_key_candidate", "key_fingerprint")
    op.drop_column("composite_key_candidate", "column_count")
    op.drop_column("composite_key_candidate", "column_names")
    op.drop_column("composite_key_candidate", "table_profile_id")
    op.drop_constraint(
        op.f("uq_audit_archive_record_archive_id"), "audit_archive_record", type_="unique"
    )
    op.create_unique_constraint(
        op.f("audit_archive_record_archive_id_key"),
        "audit_archive_record",
        ["archive_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "ai_trust_snapshot",
        "blockers",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_trust_snapshot",
        "factors",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_remediation",
        "resolution_evidence",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_view_lineage_edge_target_table_id"), table_name="view_lineage_edge")
    op.drop_index(op.f("ix_view_lineage_edge_target_column_id"), table_name="view_lineage_edge")
    op.drop_index(op.f("ix_view_lineage_edge_source_table_id"), table_name="view_lineage_edge")
    op.drop_index(op.f("ix_view_lineage_edge_source_column_id"), table_name="view_lineage_edge")
    op.drop_index(op.f("ix_view_lineage_edge_organization_id"), table_name="view_lineage_edge")
    op.drop_index("ix_view_lineage_edge_org_target", table_name="view_lineage_edge")
    op.drop_index(op.f("ix_view_lineage_edge_datasource_id"), table_name="view_lineage_edge")
    op.drop_index("ix_view_lineage_edge_datasource", table_name="view_lineage_edge")
    op.drop_table("view_lineage_edge")
    op.drop_index(
        op.f("ix_procedure_lineage_edge_target_table_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index(
        op.f("ix_procedure_lineage_edge_target_column_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index(
        op.f("ix_procedure_lineage_edge_source_table_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index(
        op.f("ix_procedure_lineage_edge_source_column_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index(
        op.f("ix_procedure_lineage_edge_organization_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index("ix_procedure_lineage_edge_org_target", table_name="procedure_lineage_edge")
    op.drop_index(
        op.f("ix_procedure_lineage_edge_datasource_id"), table_name="procedure_lineage_edge"
    )
    op.drop_index("ix_procedure_lineage_edge_datasource", table_name="procedure_lineage_edge")
    op.drop_table("procedure_lineage_edge")
    op.drop_index(
        op.f("ix_freshness_watermark_config_table_id"), table_name="freshness_watermark_config"
    )
    op.drop_index(
        op.f("ix_freshness_watermark_config_organization_id"),
        table_name="freshness_watermark_config",
    )
    op.drop_index(
        op.f("ix_freshness_watermark_config_datasource_id"), table_name="freshness_watermark_config"
    )
    op.drop_table("freshness_watermark_config")
    op.drop_index("ix_freshness_observation_table_time", table_name="freshness_observation")
    op.drop_index(op.f("ix_freshness_observation_table_id"), table_name="freshness_observation")
    op.drop_index(
        op.f("ix_freshness_observation_organization_id"), table_name="freshness_observation"
    )
    op.drop_index(
        op.f("ix_freshness_observation_datasource_id"), table_name="freshness_observation"
    )
    op.drop_table("freshness_observation")
    op.drop_index(op.f("ix_vector_embedding_organization_id"), table_name="vector_embedding")
    op.drop_index("ix_vector_embedding_org_type", table_name="vector_embedding")
    op.drop_index(op.f("ix_vector_embedding_object_id"), table_name="vector_embedding")
    op.drop_index(op.f("ix_vector_embedding_datasource_id"), table_name="vector_embedding")
    op.drop_table("vector_embedding")
    op.drop_index(op.f("ix_search_index_organization_id"), table_name="search_index")
    op.drop_index("ix_search_index_org_status", table_name="search_index")
    op.drop_table("search_index")
    op.drop_index("ix_negative_assertion_suppression", table_name="negative_assertion")
    op.drop_index(op.f("ix_negative_assertion_subject_id"), table_name="negative_assertion")
    op.drop_index(op.f("ix_negative_assertion_organization_id"), table_name="negative_assertion")
    op.drop_index("ix_negative_assertion_org_type", table_name="negative_assertion")
    op.drop_index("ix_negative_assertion_org_subject", table_name="negative_assertion")
    op.drop_table("negative_assertion")
    op.drop_index("ix_consumption_record_resource", table_name="consumption_record")
    op.drop_index(op.f("ix_consumption_record_organization_id"), table_name="consumption_record")
    op.drop_index(op.f("ix_consumption_record_correlation_id"), table_name="consumption_record")
    op.drop_index("ix_consumption_record_consumer", table_name="consumption_record")
    op.drop_table("consumption_record")
    # ### end Alembic commands ###
