"""graph perspective (KG-5)

Revision ID: 2f9b7e13a4c6
Revises: 99823f633c68
Create Date: 2026-08-30 18:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2f9b7e13a4c6"
down_revision: str | Sequence[str] | None = "99823f633c68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_perspective",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("owner_principal", sa.String(length=255), nullable=False),
        sa.Column("allowed_viewer_roles", sa.JSON(), nullable=False),
        sa.Column("view_state", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_graph_perspective_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_graph_perspective_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_perspective")),
    )
    op.create_index(
        op.f("ix_graph_perspective_organization_id"),
        "graph_perspective",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_perspective_datasource_id"),
        "graph_perspective",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_perspective_owner_principal"),
        "graph_perspective",
        ["owner_principal"],
        unique=False,
    )
    op.create_index(
        "ix_graph_perspective_org_owner",
        "graph_perspective",
        ["organization_id", "owner_principal"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_graph_perspective_org_owner", table_name="graph_perspective")
    op.drop_index(
        op.f("ix_graph_perspective_owner_principal"), table_name="graph_perspective"
    )
    op.drop_index(
        op.f("ix_graph_perspective_datasource_id"), table_name="graph_perspective"
    )
    op.drop_index(
        op.f("ix_graph_perspective_organization_id"), table_name="graph_perspective"
    )
    op.drop_table("graph_perspective")
    # ### end Alembic commands ###
