"""enterprise foundation

Revision ID: 5a18fac50ae9
Revises:
Create Date: 2026-08-25 00:12:02.105681
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a18fac50ae9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
        sa.UniqueConstraint("slug", name=op.f("uq_organization_slug")),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("principal_type", sa.String(length=30), nullable=False),
        sa.Column("action", sa.String(length=150), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("source_ip", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_audit_event_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index("ix_audit_correlation", "audit_event", ["correlation_id"], unique=False)
    op.create_index(
        op.f("ix_audit_event_organization_id"), "audit_event", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_org_occurred", "audit_event", ["organization_id", "occurred_at"], unique=False
    )
    op.create_table(
        "line_of_business",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_line_of_business_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_line_of_business")),
        sa.UniqueConstraint(
            "organization_id", "code", name=op.f("uq_line_of_business_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_line_of_business_organization_id"),
        "line_of_business",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_outbox_event_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_event")),
    )
    op.create_index(
        op.f("ix_outbox_event_organization_id"), "outbox_event", ["organization_id"], unique=False
    )
    op.create_index("ix_outbox_pending", "outbox_event", ["status", "occurred_at"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("line_of_business_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_of_business_id"],
            ["line_of_business.id"],
            name=op.f("fk_project_line_of_business_id_line_of_business"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_project_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("organization_id", "slug", name=op.f("uq_project_organization_id")),
    )
    op.create_index(
        op.f("ix_project_line_of_business_id"), "project", ["line_of_business_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_organization_id"), "project", ["organization_id"], unique=False
    )
    op.create_table(
        "datasource",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("line_of_business_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("connector_type", sa.String(length=50), nullable=False),
        sa.Column("dialect", sa.String(length=50), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("network_zone", sa.String(length=100), nullable=False),
        sa.Column("credential_reference", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_of_business_id"],
            ["line_of_business.id"],
            name=op.f("fk_datasource_line_of_business_id_line_of_business"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_datasource_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_datasource_project_id_project"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasource")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_datasource_project_id")),
    )
    op.create_index(
        op.f("ix_datasource_line_of_business_id"),
        "datasource",
        ["line_of_business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_datasource_organization_id"), "datasource", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_datasource_project_id"), "datasource", ["project_id"], unique=False)
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("temporal_workflow_id", sa.String(length=255), nullable=True),
        sa.Column("discovered_catalogs", sa.Integer(), nullable=False),
        sa.Column("discovered_schemas", sa.Integer(), nullable=False),
        sa.Column("discovered_tables", sa.Integer(), nullable=False),
        sa.Column("discovered_columns", sa.Integer(), nullable=False),
        sa.Column("error_class", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_analysis_run_datasource_id_datasource"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_analysis_run_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
        sa.UniqueConstraint(
            "temporal_workflow_id", name=op.f("uq_analysis_run_temporal_workflow_id")
        ),
    )
    op.create_index(
        op.f("ix_analysis_run_datasource_id"), "analysis_run", ["datasource_id"], unique=False
    )
    op.create_index(
        "ix_analysis_run_org_status", "analysis_run", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_run_organization_id"), "analysis_run", ["organization_id"], unique=False
    )
    op.create_table(
        "metadata_catalog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_metadata_catalog_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_metadata_catalog_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_catalog")),
        sa.UniqueConstraint(
            "datasource_id", "name", name=op.f("uq_metadata_catalog_datasource_id")
        ),
    )
    op.create_index(
        op.f("ix_metadata_catalog_datasource_id"),
        "metadata_catalog",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_catalog_organization_id"),
        "metadata_catalog",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "metadata_schema",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["metadata_catalog.id"],
            name=op.f("fk_metadata_schema_catalog_id_metadata_catalog"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_metadata_schema_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_schema")),
        sa.UniqueConstraint("catalog_id", "name", name=op.f("uq_metadata_schema_catalog_id")),
    )
    op.create_index(
        op.f("ix_metadata_schema_catalog_id"), "metadata_schema", ["catalog_id"], unique=False
    )
    op.create_index(
        op.f("ix_metadata_schema_organization_id"),
        "metadata_schema",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "metadata_table",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("schema_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("object_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_metadata_table_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_metadata_table_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["metadata_schema.id"],
            name=op.f("fk_metadata_table_schema_id_metadata_schema"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_table")),
        sa.UniqueConstraint("schema_id", "name", name=op.f("uq_metadata_table_schema_id")),
    )
    op.create_index(
        op.f("ix_metadata_table_datasource_id"), "metadata_table", ["datasource_id"], unique=False
    )
    op.create_index(
        "ix_metadata_table_org_status",
        "metadata_table",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_table_organization_id"),
        "metadata_table",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_table_schema_id"), "metadata_table", ["schema_id"], unique=False
    )
    op.create_table(
        "metadata_column",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("physical_type", sa.String(length=255), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("default_expression", sa.Text(), nullable=True),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_metadata_column_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_metadata_column_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_column")),
        sa.UniqueConstraint("table_id", "name", name=op.f("uq_metadata_column_table_id")),
    )
    op.create_index(
        "ix_metadata_column_org_class",
        "metadata_column",
        ["organization_id", "classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_column_organization_id"),
        "metadata_column",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_column_table_id"), "metadata_column", ["table_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metadata_column_table_id"), table_name="metadata_column")
    op.drop_index(op.f("ix_metadata_column_organization_id"), table_name="metadata_column")
    op.drop_index("ix_metadata_column_org_class", table_name="metadata_column")
    op.drop_table("metadata_column")
    op.drop_index(op.f("ix_metadata_table_schema_id"), table_name="metadata_table")
    op.drop_index(op.f("ix_metadata_table_organization_id"), table_name="metadata_table")
    op.drop_index("ix_metadata_table_org_status", table_name="metadata_table")
    op.drop_index(op.f("ix_metadata_table_datasource_id"), table_name="metadata_table")
    op.drop_table("metadata_table")
    op.drop_index(op.f("ix_metadata_schema_organization_id"), table_name="metadata_schema")
    op.drop_index(op.f("ix_metadata_schema_catalog_id"), table_name="metadata_schema")
    op.drop_table("metadata_schema")
    op.drop_index(op.f("ix_metadata_catalog_organization_id"), table_name="metadata_catalog")
    op.drop_index(op.f("ix_metadata_catalog_datasource_id"), table_name="metadata_catalog")
    op.drop_table("metadata_catalog")
    op.drop_index(op.f("ix_analysis_run_organization_id"), table_name="analysis_run")
    op.drop_index("ix_analysis_run_org_status", table_name="analysis_run")
    op.drop_index(op.f("ix_analysis_run_datasource_id"), table_name="analysis_run")
    op.drop_table("analysis_run")
    op.drop_index(op.f("ix_datasource_project_id"), table_name="datasource")
    op.drop_index(op.f("ix_datasource_organization_id"), table_name="datasource")
    op.drop_index(op.f("ix_datasource_line_of_business_id"), table_name="datasource")
    op.drop_table("datasource")
    op.drop_index(op.f("ix_project_organization_id"), table_name="project")
    op.drop_index(op.f("ix_project_line_of_business_id"), table_name="project")
    op.drop_table("project")
    op.drop_index("ix_outbox_pending", table_name="outbox_event")
    op.drop_index(op.f("ix_outbox_event_organization_id"), table_name="outbox_event")
    op.drop_table("outbox_event")
    op.drop_index(op.f("ix_line_of_business_organization_id"), table_name="line_of_business")
    op.drop_table("line_of_business")
    op.drop_index("ix_audit_org_occurred", table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_organization_id"), table_name="audit_event")
    op.drop_index("ix_audit_correlation", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_table("organization")
    # ### end Alembic commands ###
