"""composite key candidate (PR-1)

Revision ID: 6500275e1d36
Revises: f3a8c62d9e17
Create Date: 2026-08-30 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6500275e1d36"
down_revision: str | Sequence[str] | None = "f3a8c62d9e17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "composite_key_candidate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("column_ids", sa.JSON(), nullable=False),
        sa.Column("detection_rule", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("review_reason", sa.String(length=2000), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_composite_key_candidate_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_composite_key_candidate_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_composite_key_candidate_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_composite_key_candidate")),
    )
    op.create_index(
        op.f("ix_composite_key_candidate_organization_id"),
        "composite_key_candidate",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_composite_key_candidate_datasource_id"),
        "composite_key_candidate",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        "ix_composite_key_candidate_table",
        "composite_key_candidate",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        "ix_composite_key_candidate_org_status",
        "composite_key_candidate",
        ["organization_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_composite_key_candidate_org_status", table_name="composite_key_candidate"
    )
    op.drop_index("ix_composite_key_candidate_table", table_name="composite_key_candidate")
    op.drop_index(
        op.f("ix_composite_key_candidate_datasource_id"),
        table_name="composite_key_candidate",
    )
    op.drop_index(
        op.f("ix_composite_key_candidate_organization_id"),
        table_name="composite_key_candidate",
    )
    op.drop_table("composite_key_candidate")
    # ### end Alembic commands ###
