"""complete glossary stewardship

Revision ID: 7fbc5568a81f
Revises: ab31d7e4c920
Create Date: 2026-08-28 08:33:51.974965
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7fbc5568a81f"
down_revision: str | Sequence[str] | None = "ab31d7e4c920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "glossary_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("category_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_glossary_category_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["glossary_category.id"],
            name=op.f("fk_glossary_category_parent_id_glossary_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_category")),
        sa.UniqueConstraint(
            "organization_id", "category_key", name=op.f("uq_glossary_category_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_glossary_category_organization_id"),
        "glossary_category",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_category_parent_id"), "glossary_category", ["parent_id"], unique=False
    )
    op.create_table(
        "ownership_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("rule_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("match_field", sa.String(length=30), nullable=False),
        sa.Column("match_pattern", sa.String(length=255), nullable=False),
        sa.Column("owner_type", sa.String(length=30), nullable=False),
        sa.Column("owner_principal", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_ownership_rule_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ownership_rule")),
        sa.UniqueConstraint(
            "organization_id", "rule_key", name=op.f("uq_ownership_rule_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_ownership_rule_organization_id"),
        "ownership_rule",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "bulk_stewardship_operation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("subject_ids", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("governance_review_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("applied_by", sa.String(length=255), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["governance_review_id"],
            ["governance_review.id"],
            name=op.f("fk_bulk_stewardship_operation_governance_review_id_governance_review"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_bulk_stewardship_operation_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bulk_stewardship_operation")),
        sa.UniqueConstraint(
            "governance_review_id", name=op.f("uq_bulk_stewardship_operation_governance_review_id")
        ),
    )
    op.create_index(
        op.f("ix_bulk_stewardship_operation_organization_id"),
        "bulk_stewardship_operation",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_bulk_stewardship_org_status",
        "bulk_stewardship_operation",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "ownership_assignment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=30), nullable=False),
        sa.Column("subject_id", sa.String(length=100), nullable=False),
        sa.Column("owner_type", sa.String(length=30), nullable=False),
        sa.Column("owner_principal", sa.String(length=255), nullable=False),
        sa.Column("assignment_kind", sa.String(length=30), nullable=False),
        sa.Column("source_rule_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("assigned_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_ownership_assignment_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_rule_id"],
            ["ownership_rule.id"],
            name=op.f("fk_ownership_assignment_source_rule_id_ownership_rule"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ownership_assignment")),
        sa.UniqueConstraint(
            "organization_id",
            "subject_type",
            "subject_id",
            "owner_type",
            "owner_principal",
            name="uq_ownership_assignment_subject_owner",
        ),
    )
    op.create_index(
        "ix_ownership_assignment_org_subject",
        "ownership_assignment",
        ["organization_id", "subject_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ownership_assignment_organization_id"),
        "ownership_assignment",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ownership_assignment_source_rule_id"),
        "ownership_assignment",
        ["source_rule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ownership_assignment_subject_id"),
        "ownership_assignment",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "glossary_conflict",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("conflict_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("position_a", sa.JSON(), nullable=False),
        sa.Column("position_b", sa.JSON(), nullable=False),
        sa.Column("assigned_owner", sa.String(length=255), nullable=True),
        sa.Column("raised_by", sa.String(length=255), nullable=False),
        sa.Column("proposed_resolution", sa.String(length=30), nullable=True),
        sa.Column("proposed_definition", sa.Text(), nullable=True),
        sa.Column("resolution_rationale", sa.String(length=2000), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_glossary_conflict_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["glossary_term.id"],
            name=op.f("fk_glossary_conflict_term_id_glossary_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_conflict")),
    )
    op.create_index(
        "ix_glossary_conflict_org_status",
        "glossary_conflict",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_conflict_organization_id"),
        "glossary_conflict",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_conflict_term_id"), "glossary_conflict", ["term_id"], unique=False
    )
    op.create_table(
        "coverage_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=True),
        sa.Column("table_count", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("computed_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_coverage_snapshot_datasource_id_datasource"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_coverage_snapshot_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_snapshot")),
    )
    op.create_index(
        op.f("ix_coverage_snapshot_datasource_id"),
        "coverage_snapshot",
        ["datasource_id"],
        unique=False,
    )
    op.create_index(
        "ix_coverage_snapshot_org_created",
        "coverage_snapshot",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coverage_snapshot_organization_id"),
        "coverage_snapshot",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "asset_certification",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("rationale", sa.String(length=2000), nullable=False),
        sa.Column("certified_by", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_asset_certification_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_asset_certification_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_certification")),
    )
    op.create_index(
        "ix_asset_certification_org_status",
        "asset_certification",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_certification_organization_id"),
        "asset_certification",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_asset_certification_table_id"), "asset_certification", ["table_id"], unique=False
    )
    op.create_table(
        "glossary_link_proposal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("source_annotation_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("governance_review_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["governance_review_id"],
            ["governance_review.id"],
            name=op.f("fk_glossary_link_proposal_governance_review_id_governance_review"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_glossary_link_proposal_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_annotation_id"],
            ["metadata_business_annotation.id"],
            name=op.f(
                "fk_glossary_link_proposal_source_annotation_id_metadata_business_annotation"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_glossary_link_proposal_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["glossary_term.id"],
            name=op.f("fk_glossary_link_proposal_term_id_glossary_term"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_link_proposal")),
        sa.UniqueConstraint(
            "governance_review_id", name=op.f("uq_glossary_link_proposal_governance_review_id")
        ),
        sa.UniqueConstraint(
            "table_id", "term_id", "source_annotation_id", name="uq_glossary_link_proposal_evidence"
        ),
    )
    op.create_index(
        "ix_glossary_link_proposal_org_status",
        "glossary_link_proposal",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_link_proposal_organization_id"),
        "glossary_link_proposal",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_link_proposal_source_annotation_id"),
        "glossary_link_proposal",
        ["source_annotation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_link_proposal_table_id"),
        "glossary_link_proposal",
        ["table_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_link_proposal_term_id"),
        "glossary_link_proposal",
        ["term_id"],
        unique=False,
    )
    op.add_column(
        "asset_term_link",
        sa.Column("link_type", sa.String(length=30), server_default="MANUAL", nullable=False),
    )
    op.add_column(
        "asset_term_link",
        sa.Column("confidence", sa.Float(), server_default="1.0", nullable=False),
    )
    op.add_column("asset_term_link", sa.Column("source_annotation_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_asset_term_link_source_annotation_id"),
        "asset_term_link",
        ["source_annotation_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_asset_term_link_source_annotation_id_metadata_business_annotation"),
        "asset_term_link",
        "metadata_business_annotation",
        ["source_annotation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("glossary_term", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.add_column(
        "glossary_term",
        sa.Column(
            "lifecycle_status", sa.String(length=30), server_default="ACTIVE", nullable=False
        ),
    )
    op.add_column("glossary_term", sa.Column("deprecated_by", sa.String(length=255), nullable=True))
    op.add_column(
        "glossary_term", sa.Column("deprecated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "glossary_term", sa.Column("deprecation_reason", sa.String(length=2000), nullable=True)
    )
    op.create_index(
        op.f("ix_glossary_term_category_id"), "glossary_term", ["category_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_glossary_term_category_id_glossary_category"),
        "glossary_term",
        "glossary_category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "glossary_term_version",
        sa.Column("synonyms", sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    )
    op.alter_column("asset_term_link", "link_type", server_default=None)
    op.alter_column("asset_term_link", "confidence", server_default=None)
    op.alter_column("glossary_term", "lifecycle_status", server_default=None)
    op.alter_column("glossary_term_version", "synonyms", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("glossary_term_version", "synonyms")
    op.drop_constraint(
        op.f("fk_glossary_term_category_id_glossary_category"), "glossary_term", type_="foreignkey"
    )
    op.drop_index(op.f("ix_glossary_term_category_id"), table_name="glossary_term")
    op.drop_column("glossary_term", "deprecation_reason")
    op.drop_column("glossary_term", "deprecated_at")
    op.drop_column("glossary_term", "deprecated_by")
    op.drop_column("glossary_term", "lifecycle_status")
    op.drop_column("glossary_term", "category_id")
    op.drop_constraint(
        op.f("fk_asset_term_link_source_annotation_id_metadata_business_annotation"),
        "asset_term_link",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_asset_term_link_source_annotation_id"), table_name="asset_term_link")
    op.drop_column("asset_term_link", "source_annotation_id")
    op.drop_column("asset_term_link", "confidence")
    op.drop_column("asset_term_link", "link_type")
    op.drop_index(op.f("ix_glossary_link_proposal_term_id"), table_name="glossary_link_proposal")
    op.drop_index(op.f("ix_glossary_link_proposal_table_id"), table_name="glossary_link_proposal")
    op.drop_index(
        op.f("ix_glossary_link_proposal_source_annotation_id"), table_name="glossary_link_proposal"
    )
    op.drop_index(
        op.f("ix_glossary_link_proposal_organization_id"), table_name="glossary_link_proposal"
    )
    op.drop_index("ix_glossary_link_proposal_org_status", table_name="glossary_link_proposal")
    op.drop_table("glossary_link_proposal")
    op.drop_index(op.f("ix_asset_certification_table_id"), table_name="asset_certification")
    op.drop_index(op.f("ix_asset_certification_organization_id"), table_name="asset_certification")
    op.drop_index("ix_asset_certification_org_status", table_name="asset_certification")
    op.drop_table("asset_certification")
    op.drop_index(op.f("ix_coverage_snapshot_organization_id"), table_name="coverage_snapshot")
    op.drop_index("ix_coverage_snapshot_org_created", table_name="coverage_snapshot")
    op.drop_index(op.f("ix_coverage_snapshot_datasource_id"), table_name="coverage_snapshot")
    op.drop_table("coverage_snapshot")
    op.drop_index(op.f("ix_glossary_conflict_term_id"), table_name="glossary_conflict")
    op.drop_index(op.f("ix_glossary_conflict_organization_id"), table_name="glossary_conflict")
    op.drop_index("ix_glossary_conflict_org_status", table_name="glossary_conflict")
    op.drop_table("glossary_conflict")
    op.drop_index(op.f("ix_ownership_assignment_subject_id"), table_name="ownership_assignment")
    op.drop_index(op.f("ix_ownership_assignment_source_rule_id"), table_name="ownership_assignment")
    op.drop_index(
        op.f("ix_ownership_assignment_organization_id"), table_name="ownership_assignment"
    )
    op.drop_index("ix_ownership_assignment_org_subject", table_name="ownership_assignment")
    op.drop_table("ownership_assignment")
    op.drop_index("ix_bulk_stewardship_org_status", table_name="bulk_stewardship_operation")
    op.drop_index(
        op.f("ix_bulk_stewardship_operation_organization_id"),
        table_name="bulk_stewardship_operation",
    )
    op.drop_table("bulk_stewardship_operation")
    op.drop_index(op.f("ix_ownership_rule_organization_id"), table_name="ownership_rule")
    op.drop_table("ownership_rule")
    op.drop_index(op.f("ix_glossary_category_parent_id"), table_name="glossary_category")
    op.drop_index(op.f("ix_glossary_category_organization_id"), table_name="glossary_category")
    op.drop_table("glossary_category")
    # ### end Alembic commands ###
