"""canonical table group (RL-2)

Revision ID: 8948cba0f342
Revises: 99823f633c68
Create Date: 2026-08-30 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8948cba0f342"
down_revision: str | Sequence[str] | None = "99823f633c68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_table_group",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("member_table_ids", sa.JSON(), nullable=False),
        sa.Column("canonical_table_id", sa.Uuid(), nullable=True),
        sa.Column("detection_rule", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("review_reason", sa.String(length=2000), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_canonical_table_group_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_table_id"],
            ["metadata_table.id"],
            name=op.f("fk_canonical_table_group_canonical_table_id_metadata_table"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_table_group")),
    )
    op.create_index(
        op.f("ix_canonical_table_group_organization_id"),
        "canonical_table_group",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_table_group_canonical_table_id"),
        "canonical_table_group",
        ["canonical_table_id"],
        unique=False,
    )
    op.create_index(
        "ix_canonical_table_group_org_status",
        "canonical_table_group",
        ["organization_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_canonical_table_group_org_status", table_name="canonical_table_group")
    op.drop_index(
        op.f("ix_canonical_table_group_canonical_table_id"),
        table_name="canonical_table_group",
    )
    op.drop_index(
        op.f("ix_canonical_table_group_organization_id"),
        table_name="canonical_table_group",
    )
    op.drop_table("canonical_table_group")
    # ### end Alembic commands ###
