"""scope stewardship coverage history and preserve dbt column metadata

Revision ID: 9284d3ee7c0e
Revises: 7fbc5568a81f
Create Date: 2026-08-28 10:07:00.649921
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9284d3ee7c0e"
down_revision: str | Sequence[str] | None = "7fbc5568a81f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coverage_snapshot", sa.Column("domain_id", sa.Uuid(), nullable=True))
    op.add_column("coverage_snapshot", sa.Column("line_of_business_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_coverage_snapshot_domain_id"), "coverage_snapshot", ["domain_id"], unique=False
    )
    op.create_index(
        op.f("ix_coverage_snapshot_line_of_business_id"),
        "coverage_snapshot",
        ["line_of_business_id"],
        unique=False,
    )
    op.create_index(
        "ix_coverage_snapshot_scope",
        "coverage_snapshot",
        ["organization_id", "domain_id", "line_of_business_id", "datasource_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_coverage_snapshot_line_of_business_id_line_of_business"),
        "coverage_snapshot",
        "line_of_business",
        ["line_of_business_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_coverage_snapshot_domain_id_business_domain"),
        "coverage_snapshot",
        "business_domain",
        ["domain_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "dbt_resource",
        sa.Column(
            "column_descriptions",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
    )
    op.add_column(
        "dbt_resource",
        sa.Column(
            "column_types",
            sa.JSON(),
            server_default=sa.text("'{}'::json"),
            nullable=False,
        ),
    )
    op.alter_column("dbt_resource", "column_descriptions", server_default=None)
    op.alter_column("dbt_resource", "column_types", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dbt_resource", "column_types")
    op.drop_column("dbt_resource", "column_descriptions")
    op.drop_constraint(
        op.f("fk_coverage_snapshot_domain_id_business_domain"),
        "coverage_snapshot",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_coverage_snapshot_line_of_business_id_line_of_business"),
        "coverage_snapshot",
        type_="foreignkey",
    )
    op.drop_index("ix_coverage_snapshot_scope", table_name="coverage_snapshot")
    op.drop_index(op.f("ix_coverage_snapshot_line_of_business_id"), table_name="coverage_snapshot")
    op.drop_index(op.f("ix_coverage_snapshot_domain_id"), table_name="coverage_snapshot")
    op.drop_column("coverage_snapshot", "line_of_business_id")
    op.drop_column("coverage_snapshot", "domain_id")
    # ### end Alembic commands ###
