"""catalog bulk actions

Revision ID: b3f7a1c94d62
Revises: d81e6c0f2a14
Create Date: 2026-08-30 13:31:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b3f7a1c94d62"
down_revision: str | Sequence[str] | None = "d81e6c0f2a14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_tag",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("tag_key", sa.String(length=100), nullable=False),
        sa.Column("tag_value", sa.String(length=500), nullable=True),
        sa.Column("applied_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_asset_tag_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["metadata_table.id"],
            name=op.f("fk_asset_tag_table_id_metadata_table"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_tag")),
        sa.UniqueConstraint("table_id", "tag_key", name=op.f("uq_asset_tag_table_id")),
    )
    op.create_index(
        op.f("ix_asset_tag_organization_id"), "asset_tag", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_asset_tag_table_id"), "asset_tag", ["table_id"], unique=False)
    op.create_index(
        "ix_asset_tag_org_key", "asset_tag", ["organization_id", "tag_key"], unique=False
    )
    op.create_table(
        "catalog_bulk_action_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("selection_mode", sa.String(length=20), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_catalog_bulk_action_run_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_bulk_action_run")),
    )
    op.create_index(
        op.f("ix_catalog_bulk_action_run_organization_id"),
        "catalog_bulk_action_run",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_catalog_bulk_action_run_org_action",
        "catalog_bulk_action_run",
        ["organization_id", "action", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalog_bulk_action_run_org_action", table_name="catalog_bulk_action_run")
    op.drop_index(
        op.f("ix_catalog_bulk_action_run_organization_id"), table_name="catalog_bulk_action_run"
    )
    op.drop_table("catalog_bulk_action_run")
    op.drop_index("ix_asset_tag_org_key", table_name="asset_tag")
    op.drop_index(op.f("ix_asset_tag_table_id"), table_name="asset_tag")
    op.drop_index(op.f("ix_asset_tag_organization_id"), table_name="asset_tag")
    op.drop_table("asset_tag")
    # ### end Alembic commands ###
