"""governed query execution

Revision ID: cb0e8b95925b
Revises: 5a18fac50ae9
Create Date: 2026-08-25 00:22:05.854190
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cb0e8b95925b"
down_revision: str | Sequence[str] | None = "5a18fac50ae9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("datasource_id", sa.Uuid(), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("dialect", sa.String(length=50), nullable=False),
        sa.Column("sql_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_sql", sa.Text(), nullable=True),
        sa.Column("referenced_tables", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("semantic_version", sa.String(length=100), nullable=True),
        sa.Column("plan_cost", sa.Float(), nullable=True),
        sa.Column("warehouse_query_id", sa.String(length=255), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("error_class", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasource.id"],
            name=op.f("fk_query_execution_datasource_id_datasource"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_query_execution_organization_id_organization"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_execution")),
    )
    op.create_index(
        op.f("ix_query_execution_datasource_id"), "query_execution", ["datasource_id"], unique=False
    )
    op.create_index(
        "ix_query_execution_org_created",
        "query_execution",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_query_execution_org_status",
        "query_execution",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_query_execution_organization_id"),
        "query_execution",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_execution_organization_id"), table_name="query_execution")
    op.drop_index("ix_query_execution_org_status", table_name="query_execution")
    op.drop_index("ix_query_execution_org_created", table_name="query_execution")
    op.drop_index(op.f("ix_query_execution_datasource_id"), table_name="query_execution")
    op.drop_table("query_execution")
    # ### end Alembic commands ###
