apiVersion: v1
kind: Service
metadata:
  name: aida-api
  namespace: aida
  labels:
    app.kubernetes.io/name: aida-api
    app.kubernetes.io/part-of: aida-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aida-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
