#!/usr/bin/env python3
"""Regenerate the published metadata GraphQL schema (R11-GQL01, design section 13).

Writes two files from live code, with no timestamp in either, so `--check` can
compare them byte for byte (the same contract as
`scripts/generate_engine_capability_matrix.py`):

* `Docs/90-reference/graphql-schema.graphql` -- the SDL `POST /graphql` serves,
  printed from `aida.graphql_schema.metadata_schema`, under a header naming the
  schema version (`GRAPHQL_SCHEMA_VERSION`).
* `Docs/90-reference/graphql-schema.md` -- the reference page: endpoint,
  demand limits (`aida.graphql_limits.DEFAULT_LIMITS`) and every stable error
  code (`REFUSAL_CODES`, `EXECUTION_ERROR_CODES`).

**Compatibility is checked here, not through OpenAPI.** The OpenAPI baseline
sees one opaque `POST /graphql`; it cannot see a field removed or an argument
made required. This script compares the committed SDL with the current one
using graphql-core's `find_breaking_changes`, and a breaking change is only
publishable under a new `GRAPHQL_SCHEMA_VERSION`. Additive changes (a new
field, a new optional argument) keep the version.

Usage:
    python scripts/generate_graphql_schema.py            # write both files
    python scripts/generate_graphql_schema.py --check    # fail if stale or incompatible
    python scripts/generate_graphql_schema.py --stdout   # print the SDL only
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

from graphql import build_schema, find_breaking_changes  # noqa: E402

from aida.graphql_limits import (  # noqa: E402
    DEFAULT_LIMITS,
    EXECUTION_ERROR_CODES,
    REFUSAL_CODES,
)
from aida.graphql_schema import GRAPHQL_SCHEMA_VERSION, metadata_schema  # noqa: E402

SDL_PATH = REPO_ROOT / "Docs" / "90-reference" / "graphql-schema.graphql"
MD_PATH = REPO_ROOT / "Docs" / "90-reference" / "graphql-schema.md"

_VERSION_LINE = re.compile(r"^# Schema version: (?P<version>\S+)$", re.MULTILINE)


def render_sdl() -> str:
    header = "\n".join(
        [
            "# Atlas metadata GraphQL schema -- POST /graphql (R11-GQL01).",
            "# Generated by scripts/generate_graphql_schema.py. Do not edit by hand;",
            "# --check fails when this file is stale or a breaking change keeps its version.",
            f"# Schema version: {GRAPHQL_SCHEMA_VERSION}",
            "",
        ]
    )
    return header + "\n" + metadata_schema.as_str().rstrip() + "\n"


def render_markdown() -> str:
    limits = DEFAULT_LIMITS
    before, during, after = "before execution", "while resolving", "after execution"
    limit_rows = [
        ("Request body", f"{limits.max_request_bytes} bytes", before, "REQUEST_TOO_LARGE"),
        ("Document tokens", str(limits.max_tokens), before, "DOCUMENT_TOO_LARGE"),
        ("Field depth", str(limits.max_depth), before, "DEPTH_LIMIT_EXCEEDED"),
        ("Aliases (fragments expanded)", str(limits.max_aliases), before, "ALIAS_LIMIT_EXCEEDED"),
        ("Page size (`first`)", f"1 to {limits.max_page_size}", before, "PAGE_SIZE_EXCEEDED"),
        (
            "Returned objects (an upper bound, estimated)",
            str(limits.max_nodes),
            before,
            "NODE_BUDGET_EXCEEDED",
        ),
        (
            "String argument or variable",
            f"{limits.max_string_argument_length} characters",
            before,
            "ARGUMENT_TOO_LONG",
        ),
        (
            "Selections visited while measuring",
            str(limits.max_selection_visits),
            before,
            "DOCUMENT_TOO_COMPLEX",
        ),
        (
            "Introspection",
            "enabled" if limits.allow_introspection else "disabled",
            before,
            "INTROSPECTION_DISABLED",
        ),
        (
            "Datasources an organization-wide `tables` listing may decide",
            str(limits.max_scope_datasources),
            during,
            "SCOPE_TOO_BROAD",
        ),
        ("Resolver deadline", f"{limits.deadline_seconds:g} seconds", during, "DEADLINE_EXCEEDED"),
        (
            "Response body, and returned objects counted",
            f"{limits.max_response_bytes} bytes",
            after,
            "RESPONSE_TOO_LARGE",
        ),
    ]
    lines = [
        "# Metadata GraphQL reference",
        "",
        "**Generated file. Do not edit by hand.** Regenerate with",
        "`python scripts/generate_graphql_schema.py`; `--check` fails when this page or",
        "the SDL beside it is stale, or when a breaking schema change keeps its version.",
        "",
        f"- Endpoint: `POST /graphql`. Schema version: **{GRAPHQL_SCHEMA_VERSION}**.",
        "- The SDL is [graphql-schema.graphql](graphql-schema.graphql).",
        "- Read-only: `query` operations over catalog metadata. No field executes",
        "  against a source; governed execution is tracker row R11-GQL02.",
        "- Authenticated and role-gated like the REST catalog reads. Each field is",
        "  decided exactly as the REST route it answers for decides it -- the mapping",
        "  is in the docstring of `aida.graphql_reads`.",
        "- One named operation per request (`operationName` is required); HTTP",
        "  batching and multi-operation documents are refused.",
        "- Cursors are the same opaque keyset cursors the REST list routes return.",
        "",
        "## Demand limits",
        "",
        "A limit checked before execution refuses the document before any resolver",
        "runs, so a refused document costs its parse and nothing else.",
        "",
        "| Limit | Value | Checked | Code |",
        "|---|---|---|---|",
    ]
    lines += [f"| {name} | {value} | {when} | `{code}` |" for name, value, when, code in limit_rows]
    lines += [
        "",
        "## Refusal codes (document refused, no `data`)",
        "",
        "| Code | HTTP status |",
        "|---|---|",
    ]
    lines += [f"| `{code}` | {status} |" for code, status in REFUSAL_CODES.items()]
    lines += [
        "",
        "## Execution codes (HTTP 200, in `errors[].extensions.code`)",
        "",
        "Field-level codes null only the field that raised them. Messages are the",
        "code itself: never SQL, a credential or an object name.",
        "",
        "| Code | Meaning |",
        "|---|---|",
    ]
    lines += [f"| `{code}` | {meaning} |" for code, meaning in EXECUTION_ERROR_CODES.items()]
    lines.append("")
    return "\n".join(lines)


def committed_version(sdl_text: str) -> str | None:
    match = _VERSION_LINE.search(sdl_text)
    return match.group("version") if match else None


def breaking_changes(old_sdl: str, new_sdl: str) -> list[str]:
    """Breaking changes from `old_sdl` to `new_sdl`, as graphql-core describes them."""
    changes = find_breaking_changes(build_schema(old_sdl), build_schema(new_sdl))
    return sorted(f"{change.type.name}: {change.description}" for change in changes)


def compatibility_problems(committed_sdl: str, current_sdl: str) -> list[str]:
    """Empty when the current schema may replace the committed one."""
    changes = breaking_changes(committed_sdl, current_sdl)
    if changes and committed_version(committed_sdl) == committed_version(current_sdl):
        return changes
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument("--check", action="store_true", help="Fail if stale or incompatible.")
    parser.add_argument("--stdout", action="store_true", help="Print the SDL instead of writing.")
    args = parser.parse_args(argv)

    sdl = render_sdl()
    markdown = render_markdown()
    if args.stdout:
        print(sdl)
        return 0

    committed = SDL_PATH.read_text(encoding="utf-8") if SDL_PATH.exists() else None
    problems = compatibility_problems(committed, sdl) if committed is not None else []
    if problems:
        print(
            "breaking GraphQL schema change under an unchanged version "
            f"({GRAPHQL_SCHEMA_VERSION}); bump GRAPHQL_SCHEMA_VERSION in "
            "aida/graphql_schema.py or make the change additive:"
        )
        for problem in problems:
            print(f"  - {problem}")
        return 1

    if args.check:
        stale = [
            str(path.relative_to(REPO_ROOT))
            for path, content in ((SDL_PATH, sdl), (MD_PATH, markdown))
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("the published GraphQL schema is out of date; regenerate it: " + ", ".join(stale))
            return 1
        print(f"{SDL_PATH.relative_to(REPO_ROOT)} and its reference page are up to date.")
        return 0

    SDL_PATH.parent.mkdir(parents=True, exist_ok=True)
    SDL_PATH.write_text(sdl, encoding="utf-8")
    MD_PATH.write_text(markdown, encoding="utf-8")
    print(f"Wrote {SDL_PATH.relative_to(REPO_ROOT)}")
    print(f"Wrote {MD_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
