#!/usr/bin/env python3
"""R11-FP17: render the Prometheus Operator PrometheusRule from the plain rule file.

The same alert has to exist twice, because the two deployment shapes this
repository supports consume different file formats: a plain Prometheus reads
`infra/monitoring/prometheus/rules/atlas.rules.yml` off disk, and a
Prometheus-Operator cluster reads a `PrometheusRule` custom resource. Nothing
translates between them at runtime.

Two copies of twenty alert rules maintained by hand drift, and the drift is
silent in the worst possible way: the alert you edited fires in staging and not
in production, or the other way around, and nobody finds out until the incident
it was written for. So one file is the source of truth -- the plain one, because
it is the one with the reasoning comments in it -- and this script renders the
other. `tests/test_monitoring_rules.py` fails when the rendered copy is stale.

**What is lost in translation, stated rather than discovered.** YAML comments do
not survive a parse, and the plain rule file's comments are the most valuable
thing in it: they are where each placeholder threshold explains that it is a
placeholder and how to replace it. The generated resource therefore carries a
header pointing back at the source file, and every placeholder rule still says
so in its own `threshold_status` label and in its `description` annotation --
which are data, not comments, and are what an operator actually sees when the
alert pages them.

Usage::

    python scripts/generate_prometheus_rule.py            # write
    python scripts/generate_prometheus_rule.py --check     # verify
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "infra/monitoring/prometheus/rules/atlas.rules.yml"
OUTPUT_PATH = REPO_ROOT / "infra/monitoring/k8s/prometheusrule.yaml"

HEADER = """\
# GENERATED by scripts/generate_prometheus_rule.py -- do not edit by hand.
#
# The source of truth is infra/monitoring/prometheus/rules/atlas.rules.yml, and
# it is the copy to read: every placeholder threshold in this file is explained
# in a comment there, and YAML comments do not survive the parse that produced
# this resource. Edit that file and re-run the generator;
# tests/test_monitoring_rules.py fails when this copy is stale.
#
# Requires the Prometheus Operator CRDs (monitoring.coreos.com/v1). On a cluster
# without them, mount the source file into a plain Prometheus instead -- see
# ../README.md.
#
# Every alert below carries a `threshold_status` label: `structural` means the
# comparison needed no magnitude anybody had to choose, `placeholder` means the
# number is a documented starting point an operator must replace. No latency or
# backlog magnitude in this file is a measurement of this platform.
"""


class _BlockDumper(yaml.SafeDumper):
    """A dumper that keeps a multi-line PromQL expression readable.

    `yaml.safe_dump`'s default for a string containing newlines is a
    double-quoted scalar with `\\n` escapes, which turns a three-line
    `histogram_quantile(...)` into one unreadable run. A generated file nobody
    can read during an incident is a generated file nobody trusts, so
    multi-line strings are emitted as literal blocks (`|`) instead. Purely
    presentational: the parsed value is identical either way.
    """


def _block_str(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_BlockDumper.add_representer(str, _block_str)


def load_groups() -> list[dict[str, Any]]:
    """The rule groups from the plain Prometheus rule file."""
    document = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    groups = document.get("groups")
    if not isinstance(groups, list) or not groups:
        raise SystemExit(f"{SOURCE_PATH} declares no rule groups")
    return groups


def render(groups: list[dict[str, Any]]) -> str:
    resource: dict[str, Any] = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "aida-platform",
            "namespace": "aida",
            "labels": {
                "app.kubernetes.io/name": "aida-platform",
                "app.kubernetes.io/part-of": "aida-platform",
                # Most kube-prometheus-stack installations restrict which
                # PrometheusRules their Prometheus loads via `ruleSelector`.
                "release": "REPLACE_ME_PROMETHEUS_RELEASE_LABEL",
            },
        },
        "spec": {"groups": groups},
    }
    body = yaml.dump(
        resource,
        Dumper=_BlockDumper,
        sort_keys=False,
        default_flow_style=False,
        width=100,
    )
    return HEADER + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the committed resource is stale instead of rewriting it",
    )
    args = parser.parse_args(argv)
    rendered = render(load_groups())
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is stale with respect to "
                f"{SOURCE_PATH.relative_to(REPO_ROOT)}; "
                "regenerate it with `python scripts/generate_prometheus_rule.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(REPO_ROOT)} is current")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
