#!/usr/bin/env python3
"""Register a model route the way the platform requires one to be registered.

A model route is the object that decides which provider and model a governed
answer is generated by, so `review_risk_tiers` classifies it **T3** and it
cannot reach `APPROVED` without a second identity approving it. That is the
whole point of the control, and it is exactly what a seeding script is tempted
to skip: a direct `INSERT ... status='APPROVED'` produces a working
configuration and a false audit trail, and every downstream claim about
maker-checker then rests on a row nobody checked.

So this drives the real handlers, in order, with two identities:

    create_model_route   (maker: an AgentDeveloper)
    submit_model_route   (same maker -- submitting is not deciding)
    decide_governance_review  APPROVE  (checker: a different Reviewer)

The maker-checker guard inside the decision path refuses a checker whose
principal id matches the requester, so passing the same identity twice fails
rather than quietly succeeding -- run it with `--same-identity` to see that
happen, which is the cheapest possible proof that the control is live.

`credential_reference` is a *reference*, never a key: `env://GEMINI_API_KEY`
is the development-only form, and `aida.secrets` refuses the `env://` scheme
outright when `AIDA_ENVIRONMENT=production`, so a route seeded here cannot
follow the repository into a deployment.

Usage:
    python scripts/seed_model_route.py --org sample-bank \\
        --route-key gemini-bank-sql --provider GOOGLE_GEMINI \\
        --model-id gemini-2.0-flash --credential env://GEMINI_API_KEY
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from uuid import UUID

from sqlalchemy import select

from aida.config import get_settings
from aida.db import session_factory
from aida.models import ModelRouteConfiguration, Organization
from aida.schemas import GovernanceDecisionRequest, ModelRouteConfigurationCreate
from aida.security_types import SecurityContext

MAKER = "seed:agent-developer"
CHECKER = "seed:reviewer"


def _context(organization_id: UUID, principal_id: str, roles: frozenset[str]) -> SecurityContext:
    return SecurityContext(
        principal_id=principal_id,
        principal_type="USER",
        organization_id=organization_id,
        roles=roles,
    )


async def _organization_id(session: object, slug: str) -> UUID:
    organization = await session.scalar(  # type: ignore[attr-defined]
        select(Organization).where(Organization.slug == slug)
    )
    if organization is None:
        raise SystemExit(f"no organization with slug {slug!r}; seed the estate first")
    return organization.id


async def seed(args: argparse.Namespace) -> int:
    # Imported here rather than at module scope: importing a router module
    # pulls in the FastAPI app graph, and doing that at import time makes this
    # script fail for reasons unrelated to what it does.
    from aida.ai_governance_api import create_model_route, submit_model_route
    from aida.semantic_api import decide_governance_review

    settings = get_settings()
    async with session_factory() as session:
        organization_id = await _organization_id(session, args.org)
        existing = await session.scalar(
            select(ModelRouteConfiguration).where(
                ModelRouteConfiguration.organization_id == organization_id,
                ModelRouteConfiguration.route_key == args.route_key,
            )
        )
        if existing is not None:
            print(
                f"route {args.route_key!r} already exists for {args.org} "
                f"(version {existing.version}, status {existing.status}) -- nothing to do"
            )
            return 0

        maker = _context(organization_id, MAKER, frozenset({"AgentDeveloper"}))
        checker = _context(
            organization_id,
            MAKER if args.same_identity else CHECKER,
            frozenset({"Reviewer"}),
        )

        draft = await create_model_route(
            organization_id=organization_id,
            body=ModelRouteConfigurationCreate(
                route_key=args.route_key,
                display_name=args.display_name or args.route_key,
                provider_type=args.provider,
                model_id=args.model_id,
                endpoint_alias=args.endpoint_alias,
                credential_reference=args.credential,
                data_residency=args.data_residency,
                retention_policy=args.retention_policy,
                capabilities=["SQL_GENERATION", "EXPLANATION"],
                max_input_tokens=settings.model_max_input_tokens,
                max_output_tokens=settings.model_max_output_tokens,
                timeout_seconds=int(settings.model_timeout_seconds),
            ),
            context=maker,
            session=session,
            settings=settings,
        )
        print(f"drafted {draft.route_key} v{draft.version} ({draft.status})")

        review = await submit_model_route(route_id=draft.id, context=maker, session=session)
        print(f"submitted for review {review.id} (T3, maker {MAKER})")
        await session.commit()

        decided = await decide_governance_review(
            review_id=review.id,
            body=GovernanceDecisionRequest(decision="APPROVE", reason="seeded development route"),
            context=checker,
            session=session,
        )
        await session.commit()

        route = await session.get(ModelRouteConfiguration, draft.id)
        assert route is not None
        print(
            f"review {decided.status} by {decided.decided_by}; "
            f"route {route.route_key} is now {route.status}"
        )
        if route.status != "APPROVED":
            print("route did not reach APPROVED -- the decision path refused it", file=sys.stderr)
            return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--org", default="sample-bank", help="organization slug")
    parser.add_argument("--route-key", required=True)
    parser.add_argument("--display-name", default="")
    parser.add_argument(
        "--provider",
        required=True,
        choices=[
            "OPENAI",
            "GOOGLE_GEMINI",
            "AZURE_OPENAI",
            "AWS_BEDROCK",
            "GOOGLE_VERTEX",
            "OPENAI_COMPATIBLE_PRIVATE",
            "ON_PREM",
        ],
    )
    parser.add_argument("--model-id", required=True)
    parser.add_argument("--endpoint-alias", default="provider-default")
    parser.add_argument("--credential", default=None, help="a REFERENCE, never a key")
    parser.add_argument("--data-residency", default="development")
    parser.add_argument(
        "--retention-policy",
        default="PROVIDER_CONTRACT",
        choices=["ZERO_RETENTION", "BANK_MANAGED", "PROVIDER_CONTRACT"],
    )
    parser.add_argument(
        "--same-identity",
        action="store_true",
        help="approve as the maker, to demonstrate that the guard refuses it",
    )
    args = parser.parse_args()
    return asyncio.run(seed(args))


if __name__ == "__main__":
    sys.exit(main())
